### ISSUE TITLE
Invalid request error when using aws cli with s3

### ISSUE THREAD

**Issue by nmb007** [boto/botocore#1008]
I am using the following command to use AWS codedeploy to push things on s3

aws deploy push --application-name aws_test_application  --description "My First Deployment" --s3-location s3://mybucketname/test_project.zip

But I am getting the following error and I am stuck at this, unable to determine whats causing this and how to fix this :(

ERROR: "An error occurred (InvalidRequest) when calling the PutObject operation: Missing required header for this request: x-amz-content-sha256"

**Comment by jamesls** [comment]
Looks like this is a CLI issue.  Would you mind moving this over to https://github.com/aws/aws-cli so we're better able to track this question?

One thing you'll need to provide is the `--debug` logs, which will give us more information about what the CLI is doing.  Otherwise there's not much to go on.

**Comment by nmb007** [comment]
ok thanks
