### ISSUE TITLE
iot-data has duplicate ErrorMessage shapes

### ISSUE THREAD

**Issue by adimarco** [boto/botocore#1011]
The service definition for iot-data defines ErrorMessage as a String type twice, once as `ErrorMessage` on line [127](https://github.com/boto/botocore/blob/develop/botocore/data/iot-data/2015-05-28/service-2.json#L127) and again as `errorMessage` on line [332](https://github.com/boto/botocore/blob/develop/botocore/data/iot-data/2015-05-28/service-2.json#L332)

Use of "errorMessage" vs "ErrorMessage" is somewhat random throughout the rest of the service definition, but this looks like a simple case sensitivity error since they both resolve to a String type.

**Comment by jamesls** [comment]
Thanks, could you share how this is creating issues for rusoto?  It'd be helpful to pass this information along to the iot team.

**Comment by matthewkmayer** [comment]
We're generating Rust code from the JSON service definitions.  To write correct Rust code we translate classes into Pascal case.  `errorMessage` and `ErrorMessage` thus get translated into the same class and we end up with duplicate definitions for that class.

Right now @adimarco has modified our codegen to have an intermediate collection that discards duplicates, then outputs the generated code.

At first glance it appears the botocore JSON service definition could be simplified by using a single `errorMessage` type instead of two that boil down to the same `string` type.

**Comment by jamesls** [comment]
Thanks for the info, I've forwarded this request along to the iot team.

**Comment by JordonPhillips** [comment]
Closing out here since there's no actionable items for us.
