### ISSUE TITLE
No JSON object could be decoded error for empty apigateway_client.delete_base_path_mapping

### ISSUE THREAD

**Issue by Miserlou** [boto/botocore#1014]
This is a weird one.

If you have an empty API Gateway base path mapping that you want deleted, if you call

                    self.apigateway_client.delete_base_path_mapping(
                        domainName=domain_name,
                        basePath=''
                    )

You'll get an `No JSON object could be decoded` message, and that's it.

Turning on logging shows this is actually a different error, initially I thought this was related to the documentation saying ['DELET' rather than than 'DELETE'](https://docs.aws.amazon.com/apigateway/api-reference/link-relation/basepathmapping-delete/), but I think that's just a documentation error.

Turns out you actually need to pass the string "(none)" as part of your base Path mapping, ex:

                    self.apigateway_client.delete_base_path_mapping(
                        domainName=domain_name,
                        basePath='(none)'
                    )

That's clearly a bug, but is it something that should be fixed automatically in botorcore? Or reported to AWS?

**Comment by kyleknap** [comment]
I think this request should be moved to the [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199). Sure we could add a customization in botocore to inject ``'(none)'`` if an empty string is provided, but that only accounts for one client-side library/tool out of all the possible language-specific clients. It would be much better if this got changed upstream in the server logic so that all client tools are fixed without having to make any changes.

**Comment by Miserlou** [comment]
Yeah, probably.

**Comment by kyleknap** [comment]
Closing in favor of moving request to the forums.
