### ISSUE TITLE
SigV4QueryAuth:_modify_request_before_signing fails

### ISSUE THREAD

**Issue by david-dever-23-box** [boto/botocore#1036]
For s3v4-query auth, ValueError is raised in two cases:

1.  PUT Bucket: LocationConstraint is provided within the request body
2.  PUT Object

I believe that the issue arises here: https://github.com/boto/botocore/blob/develop/botocore/auth.py#L454, but the context is somewhat obtuse. Please advise.

**Comment by david-dever-23-box** [comment]
This issue was discovered when running a test script that covers s3 / s3-query / s3v4 / s3v4-query  auth types with virtual / path addressing styles; both s3v4-query cases fail with error noted above.

**Comment by david-dever-23-box** [comment]
Closing for further troubleshooting

**Comment by JordonPhillips** [comment]
How exactly are you using that? `s3v4-query` is the auth type for presigning s3 sigv4 requests, it should not be used on a client.

**Comment by david-dever-23-box** [comment]
That does not explain why the s3-query equivalent works a charm - if your logic is correct, that should also be broken, yet it isn't. Please explain your rationale.

**Comment by JordonPhillips** [comment]
The pre-signers are very different. They might work on a client, they might not.  We don't document or test either case. The use case for those signers is to pre-sign a request via `generate_presigned_url` or `generate_presigned_post` to be called later with a simple http request (e.g. `requests.get`, `curl`, etc). Even if they do work via a client you wouldn't want to use them over the regular signers because they provide no marginal benefit but use up extra resources.

Can I ask what your use case is?

**Comment by david-dever-23-box** [comment]
OK - that's reasonable - please close as wontfix

**Comment by JordonPhillips** [comment]
Will do, let me know if you have any other questions.
