### ISSUE TITLE
RTMP link cloudfront singing.

### ISSUE THREAD

**Issue by EvgeneOskin** [boto/botocore#1038]
Hello,

I guess there is a issue with signing rtmp link to Cloudfront RTMP Distribution. I've tried it as is and it does not work (the stream is not permited):

``` python
signed_url = cloudfront_signer.generate_presigned_url('rtmp://resource.cloudfront.net/cfx/st/video', date_less_than=expire_date)
```

Does python sdk support signing rtmp link?

Reference to implementation https://github.com/jasonsims/aws-cloudfront-sign/blob/f7852af0f91891d53c46afc1cc686b99c7bc75c7/lib/cloudfrontUtil.js#L67-L70

**Comment by EvgeneOskin** [comment]
I use a workaround:

```python
def sign_rtmp_link(cloudfront_signer, url, expire_date):
    cloud_front_url_prefix = 'cfx/st/'
    base, path = url.split(cloud_front_url_prefix)
    signed_path = cloudfront_signer.generate_presigned_url(
        path, date_less_than=expire_date
    )
    return base + cloud_front_url_prefix + signed_path
```

But it'll be great to remove it and use boto as is.

**Comment by jamesls** [comment]
Looking at your workaround and docs from http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-creating-signed-url-custom-policy.html, it looks like the core of the issue is that for RTMP, the resource name should just only be the path.  I'm surprised you have to strip off the `cfx/st` part though.  From the docs it looks like only the path should be included.  Their example signature is:

```
Example signed URL for an RTMP distribution:

videos/mediafile.flv?color=red&size=medium&  ...
```

**Comment by EvgeneOskin** [comment]
Hi @jamesls. 

Yes, You're right, that only path should be signed. Based on doc http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Streaming_Troubleshooting.html, for rtmp distribution the `/cfx/st` is required prefix.
> Confirm that the path for the file includes /cfx/st.

So, I guess, the path to the object (not the rtmp url path) should be signed. That's why I strip the `/cfx/st` part.
