### ISSUE TITLE
RefreshableCredentials may get wrong keys

### ISSUE THREAD

**Issue by shileiyu** [boto/botocore#1065]
The _refresh may be triggered in any accessor of key_id, secret_key or security_token.
for instance, if client access those different parts crossing the point of expiration, the client would got wrong credentials eventually.

class RefreshableCredentials(Credentials):
    @property
    def access_key(self):
        self._refresh()
        return self._access_key

    @access_key.setter
    def access_key(self, value):
        self._access_key = value

    @property
    def secret_key(self):
        self._refresh()
        return self._secret_key

    @secret_key.setter
    def secret_key(self, value):
        self._secret_key = value

    @property
    def token(self):
        self._refresh()
        return self._token

    @token.setter
    def token(self, value):
        self._token = value

Am I missing something?

**Comment by shileiyu** [comment]
I realize there's an interface named get_frozen_credentials which works correctly. I still think expose suck property may leads problem due to misuse.

**Comment by jamesls** [comment]
You are correct in your assessment, `get_frozen_credentials` was added specifically because of this issue and all the internal botocore code was switched over to this interface.

Removing these attributes would be a backwards incompatible change so we cannot remove these until the next major version bump of botocore.  Perhaps the best we can do is issue a warning that there's a potential race condition and that you should prefer `get_frozen_credentials`.

**Comment by shileiyu** [comment]
Agree, Please raise an exception when someone accesses those deprecated public properties of RefreshableCredentials.
