### ISSUE TITLE
"execute-api" should be included in the get_available_services() list

### ISSUE THREAD

**Issue by jghaines** [boto/botocore#1140]
The following code returns a list of available services

    >>> import boto3
    >>> boto3.session.Session().get_available_services()

AWSV4Sign requires a service name as part of the 'Credential' field. 'execute-api' is a valid service name. get_available_services should include it.

The list of services appears to be populated from: ./data/endpoints.json. 'execute-api' would be added there.

**Comment by JordonPhillips** [comment]
`execute-api` is not a service name or endpoint prefix for any service. How are you arriving at that value?

**Comment by jghaines** [comment]
If you create your own IAM-authenticated API Gateway service it expects AWSv4Sign-ed request to use 'execute-api' as the service name.

**Comment by JordonPhillips** [comment]
We don't currently support calling API Gateway apis from boto3, we only support calling the control plane. The signers themselves are also internal interfaces. While it is technically possible to use them, we only support their use as an internal implementation detail of botocore. That said, all they are expecting is a string, it doesn't matter where that string is sourced from.

**Comment by jghaines** [comment]
I guess it is a semantics question - should boto3.session.Session().get_available_services()
* list all AWS services, or
* only the AWS services supported by boto3

**Comment by JordonPhillips** [comment]
"execute-api" isn't an AWS service - it's an implementation detail related to API Gateway's functionality. The api's you would use that for are not AWS services.

To answer your question, `get_available_services` is intended to list supported services for the version of boto3 / botocore you have installed. For a more complete list of supported services, see [this page](https://aws.amazon.com/products/). Since you're interested in signing, you might also be interested in the list of regions and endpoints for each service [here](http://docs.aws.amazon.com/general/latest/gr/rande.html).
