### ISSUE TITLE
six version dependency (awscli / pip issue)

### ISSUE THREAD

**Issue by wyardley** [boto/botocore#1184]
per the issue described in https://github.com/aws/aws-cli/issues/2568, https://github.com/pypa/pip/issues/3165, and many other places, boto has a dependency of a version of six that won't install via pip on newer versions of OS X (including Sierra). Since six is vendored in https://github.com/boto/botocore/blob/develop/botocore/vendored/six.py, could the versioning on the dependency be relaxed in such a way that this error won't come up?

The workaround of installing the AWS CLI with `--ignore-installed six` seems less than ideal (and, in fact, if six weren't vendored, presumably could cause problems with the version mismatch?)

**Comment by dstufft** [comment]
The problem here is that we don't have a dependency on six, instead one of our dependencies has a dependency on six. So there's nothing that we can really do here except not depend on things that depend on six at all, which is hard because most 2.x/3.x compatible libraries end up depending on it.

As an aside, besides being an Amazon employee on the botocore team, I am also one of the pip maintainers. I am aware of this issue and it's on my list of things to fix within pip itself. It just hasn't bubbled up to the top of my list there yet (I'm stretched pretty thin on my time for working on pip/PyPI/etc).
