### ISSUE TITLE
python2.7 boto3 

### ISSUE THREAD

**Issue by vivekhas3** [boto/botocore#1188]
"/host/src/core/lib/foundation/s3_documents_manager/documents_util.py", line 71, in upload_to_s3
    self.client.upload_fileobj(file_obj, bucket_name,key)
  File "/usr/local/lib/python2.7/site-packages/boto3/s3/inject.py", line 426, in upload_fileobj
    return future.result()
  File "/usr/local/lib/python2.7/site-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/usr/local/lib/python2.7/site-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
ClientError: An error occurred (BadDigest) when calling the PutObject operation (reached max retries: 4): The Content-MD5 you specified did not match what we received.

This occurs randomly and i couldnt replicate on a repeated way.

boto3 version:1.4.0

**Comment by kyleknap** [comment]
Given that it is sporadic errors, it might be because of your network connectivity as the error gets thrown because the MD5 that you calculate locally and send to S3 does not match the MD5 s3 computes. This by default is retried, but it looks like it exceeds the amount of retries for this error. The best option you have is to increase the amount of retries you are doing. Unfortunately, there is not really a public interface for handling this: https://github.com/boto/botocore/issues/882. So the next best option for now would be to add try/except clauses around it and retry loops on top of the upload_fileobj call(). Let us know if you have anymore questions.

**Comment by vivekhas3** [comment]
@kyleknap Thanks. Let me try the retry mechanism by explicitly catching the exception. Will re-open If it doesnt work even after retrying
