### ISSUE TITLE
Update vendored requests library to improve performance

### ISSUE THREAD

**Issue by szilveszter** [boto/botocore#1189]
As I was profiling one of our applications, I noticed that instantiating a new boto session was taking a significant amount of time (on AWS Lambda request with cold cache it was above 100ms), and I traced it down to the way requests determines the default user agent. This was fixed in 2.8.0 ([changelog](https://github.com/kennethreitz/requests/blob/master/HISTORY.rst#280-2015-10-05), [actual diff](https://github.com/kennethreitz/requests/commit/2a635ba87d7c7c3ef75e7f2013a2cd1a207a0e1a)).

Could you update the vendored requests library's version to at least 2.8.0? I'd be happy to contribute a patch if you agree that this is a good idea.

**Comment by kyleknap** [comment]
I think I would prefer if we do the update we go to the latest version of requests, which is requested in this issue: https://github.com/boto/botocore/issues/1122. This is mainly because it has caused botocore issues in the past when we upgrade requests, especially since we patch out components of requests. So if we do update it, I think we would prefer to do it in one go. Does that makes sense/work for you? If so, I would prefer to close this out in favor of the referenced issue.

In terms of contributing a patch, feel free to try, but from experience it is not really straightforward as test tend to fail after revendoring. So a good amount of work will probably be needed to put in to upgrade and then update tests/fix possible regressions in upgrading.

**Comment by szilveszter** [comment]
I'm very sorry about opening a duplicate issue, I did go through the existing list, but wasn't thorough enough. Thanks a lot for the detailed answer, I'll close this issue. I'll take a stab at upgrading requests, hope to come back with a patch in a couple of days.
