### ISSUE TITLE
Accessing AWIS using botocore

### ISSUE THREAD

**Issue by asieira** [boto/botocore#1229]
I was wondering what the best way would be to access AWIS (https://aws.amazon.com/awis/) using the botocore code. 

Would you consider having AWIS an one of the services accessible using botocore? If so, is there any documentation on how to create a new client so that I could try contributing that code?

Any pointers and/or guidance on that would be much appreciated.

**Comment by kyleknap** [comment]
Marking as a feature request. Unfortunately, there is not much that can be done to use the service with botocore as of now. In order to get this working, we would need a `service-2.json` file, which is a JSON model that represents the API for that service. Furthermore as mentioned in our [contributing guide](https://github.com/boto/botocore/blob/develop/CONTRIBUTING.rst#contributing-code), these models are generated upstream from botocore. So we would need to get the model from our upstream source in order to pull it into botocore and we do not accept pull requests for these models.

The best that you will be able to do for now is try to write a `service-2.json` by hand for the service. Then with this `service-2.json` you can run the AWS CLI [add-model](http://docs.aws.amazon.com/cli/latest/reference/configure/add-model.html) to start using a client for that model. However, there is no guarantee that you will be able to write a working `service-2.json` for the service and there really is not any documentation on how to understand/write these models.

**Comment by asieira** [comment]
Thank you for the prompt response, @kyleknap ! 🙇 

It will in fact be hard for me to help without some guidance on how to create the JSON file. Will keep monitoring this issue in case either the AWIS integration is developed or some documentation on how to write the JSON file becomes available.
