### ISSUE TITLE
get S3 object became slow(from 1.5.71)

### ISSUE THREAD

**Issue by osamunmun** [boto/botocore#1252]
I get S3 obj like below. With botocore==1.5.70, the response time was 0.1 order. But with botocore==1.5.71(or later), the response time was over 1sec.

```
s3 = boto3.resource(
            's3',
            aws_access_key_id=access_key,
            aws_secret_access_key=secret_key
        )
obj = s3.Object(bucket, key)
obj.get()
```

- python interpreter
  - 3.6.1
- OS
  - alpine
- boto3
  - 1.4.4
- Django
  - 1.10.6

**Comment by joguSD** [comment]
This is likely due to the change from sig v2 to sig v4 by default. Sig v4 needs the region to sign the request so if the region is not properly set for the bucket you're trying to access it will have to make extra calls to figure out the region. This work is cached so it should only happen once per session.

So be sure to set the appropriate region via the `region_name` parameter when creating your session or in your configuration file.

**Comment by osamunmun** [comment]
Thank you for your advise. 
Adding `region_name` resolved this issue.
