### ISSUE TITLE
Bug: DeleteObjects in S3 module

### ISSUE THREAD

**Issue by sven-schubert** [boto/botocore#1302]
Definition of DeleteObjectsRequest in https://github.com/boto/botocore/blob/develop/botocore/data/s3/2006-03-01/service-2.json is missing the required Content-MD5 header. AWS documentation: http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html

Can you please add this?

**Comment by JordonPhillips** [comment]
This isn't something we expect users to set since the Content-MD5 is that of the whole request, so instead we [set it for them](https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L172). The same goes for any other signing header and things like Content-Length (which is also required).

**Comment by sven-schubert** [comment]
Sounds reasonable. Is there a way to determine when it is set automatically? In other calls like PutBucketAclRequest or PutBucketLifecycleRequest it is made available to the user.

**Comment by JordonPhillips** [comment]
There are several instances where it is in there incorrectly, and in botocore we [hide it](https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L986-L994). Note that there are some operations where ContentMD5 is a legitimate parameter, such as PutObject. In that case one could feasibly calculate the MD5 since the body is just the object you're uploading,
 so there's no difficulty there. [Here](https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L865-L880) is where we add the handlers to each operation where we auto-set it. Note that we have two handlers: `caluclate_md5` and `conditionally_calculate_md5`.

**Comment by sven-schubert** [comment]
Thank you very much. Exactly what i was looking for.

**Comment by castaway** [comment]
Sorry to re-open an old issue.. am trying to look at / handle this for aws-sdk-perl.. Is there a reason you have a manual list of "must have an md5", -> https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L875-L890

rather than using the service-1.json mention of it? I was about to propose (for the perl sdk), setting Content-MD5 if the json file says so, yet the file doesnt mention it for DeleteObjects, and AWS docs say it is required..

**Comment by castaway** [comment]
@JordonPhillips would it be possible to get a reply to the above? It seems a fair number of sdks use botocore's service definitions, so would it not be nicer to have the list there, rather than repeated in each sdk (and thus possibly out of sync).

Currently aws-sdk-perl is generating an md5 in code, if the service json says there should be one.
