### ISSUE TITLE
universal wheel is built with python 2.6-only version pinning on python-dateutil

### ISSUE THREAD

**Issue by mmerickel** [boto/botocore#1440]
Someone built the universal wheel for 1.10.4 using Python 2.6. This has caused the universal wheel on PyPI to include the following `Requires-Dist: python-dateutil>=2.1,<2.7.0` instead of the more relaxed `Requires-Dist: python-dateutil>=2.1,<3.0`.

```
botocore 1.10.4 has requirement python-dateutil<2.7.0,>=2.1, but you'll have python-dateutil 2.7.2 which is incompatible.
```

The `setup.py` needs to have version pins using environment markers (similar to the already-defined and redundant ordereddict and simplejson deps in the extras) instead of imperatively defined in the code in order for the metadata to get into the wheel correctly.

**Comment by mmerickel** [comment]
I see master was just completely wrong here, pinning python-dateutil for all versions of python. On the develop branch that I was looking at originally it has the imperative blocks determining what goes in install_requires. That chunk of code will only work when installing the sdist - not when building the wheel.

The only way to get the metadata correct in the wheel is to use the environment markers.

**Comment by dstufft** [comment]
The current mechanism used is an older method, but its perfectly fine to do so. It's relying on the overrides in:

https://github.com/boto/botocore/blob/298cf8456ed5a7eb5cc660a401f9ff772b51b7f8/setup.cfg#L6-L7

to take precedence over the dependencies specified in the ``setup.py``. If you inspect the Wheel, you'll see stuff like:

```
Requires-Dist: simplejson==3.3.0; python_version=="2.6"
```

That validates that this method works perfectly fine. The reason the existing wheel on PyPI doesn't have these markers reflected in them, is because we originally pinned to the Python 2.6 capable version across the board to get the issue fixed quickly, and then went back and relaxed the pins after testing. That work was completed in https://github.com/boto/botocore/pull/1433 which merged two days ago. However the last release of botocore was made on April 10th, so this just hasn't managed to get released yet.

As to why we use this method instead of the method in https://github.com/boto/botocore/pull/1441, it just comes down to compatibility. There are a number of different syntaxes for making this happen, that got added over time, each new one was nicer than the last (until we go to where we are now, which is where you can just do ``install_requires=['python-dateutil>=2.1,<2.7.0; python_version=="2.6"']``, unfortunately because these syntaxes got added over time, each one requires a newer and newer version of setuptools. The syntax used here is the least friendly to maintain, but it has the benefit of offering the widest possible support for pip/setuptools versions.

Once botocore gets a release, you'll see the version pins relaxed again. Thanks!

**Comment by mmerickel** [comment]
Sure, I didn't see it was being done in setup.cfg now. The fact of the matter is that it's not released yet. I'm just a lowly user who wants to upgrade to python-dateutil 2.7.2. :-(
