### ISSUE TITLE
Sometimes, Error happened when I use s3-select 

### ISSUE THREAD

**Issue by doublekw** [boto/botocore#1453]
TraceBack is 

    raise EventStreamError(parsed_response, self._operation_name)
botocore.exceptions.EventStreamError: An error occurred (TruncatedInput) when calling the SelectObjectContent operation: The GZIP deflator finished before all input data was read.

I don't know why it happened
Sometimes.

**Comment by joguSD** [comment]
This error is actually coming back from the service. It sounds like the compressed file stored in S3 is either corrupt or the service is otherwise having some issue decompressing the file correctly. Since this is happening on the service side we won't be able to help you much. Try asking on the S3 service [forum here](https://forums.aws.amazon.com/forum.jspa?forumID=24).

**Comment by lp060** [comment]
Hi,

Is this issue solved?What is the root cause of the error? I am also facing the same issue when concurrent threads post the request (during load test)

Is this the problem with S3 select or S3 while zipping the access logs?
