### ISSUE TITLE
Behavior for empty environment variables

### ISSUE THREAD

**Issue by posener** [boto/botocore#1460]
In most programs, empty environment variable value results in a behavior as it was not defined.
In AWS CLI, defining an empty AWS_PROFILE environment variable results in the exception: `botocore.exceptions.ProfileNotFound: The config profile () could not be found`.
Botocore searches for a profile equal to an empty string.

To my opinion it should have the same behavior as AWS_PROFILE would not have been defined: using the `[default]` profile.

* `botocore.__version__ = '1.5.75'`
* OS: GNU/Linux

**Comment by tim-finnigan** [comment]
Thanks for your patience on this issue. I brought this up with the team and commented [here](https://github.com/boto/botocore/pull/1927#issuecomment-1530249482) on the related PR. As mentioned there, changes regarding environment variables now must be considered at a cross-SDK level in order to help ensure more consistency. Please consider creating an issue in our cross-SDK repository (https://github.com/aws/aws-sdk) for further tracking if this is still something that is needed.
