### ISSUE TITLE
CloudWatchLogs get_log_events should have paginator

### ISSUE THREAD

**Issue by thehesiod** [boto/botocore#1474]
given it returns pages of results and has a nextToken

**Comment by thehesiod** [comment]
would a v2 of the API help?

**Comment by kyleknap** [comment]
That could help, but would have to be driven from the service team. I think the best/most immediate option would be to update our pagination specification to support this use case or do the one-off customization as that is more in the library's control.

**Comment by copumpkin** [comment]
IMO it would be great to have two paginators for this API, one going forwards and the other backwards. If the model gets adapted to support the unusual API, it would be nice if it could support backwards pagination too.

I also think it's unusual enough to be worth just allowing individual service-specific custom paginators, and not revamping the broader model.

**Comment by PatMyron** [comment]
related: https://github.com/boto/botocore/issues/1462

**Comment by tim-finnigan** [comment]
These are the current paginators available for CloudWatchLogs: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/logs.html#paginators. 

As mentioned in https://github.com/boto/botocore/issues/1462#issuecomment-1324113660, service teams now own their respective paginator model definitions since they are shared across SDKs. I created a new issue for tracking this specific feature request here in our cross-SDK repository: https://github.com/aws/aws-sdk/issues/422. I also reached out to the CloudWatch Logs team to see if this is something that they can implement. Please refer to that new issue for updates going forward.
