### ISSUE TITLE
Description of SQS ReceiveRequestAttemptId is ambiguous WRT correct usage

### ISSUE THREAD

**Issue by sirosen** [boto/botocore#1667]
The documentation comes from one of the service files, so this can't be fixed within botocore itself.

ReceiveRequestAttemptId is documented [here](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html) and [here](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-receiverequestattemptid-request-parameter.html) in a way that leaves an open question: should I supply this value for boto3's internal retries to function correctly?

The boto3 doc for `SQS.Client.receive_message` doesn't really clarify this. It documents correct usage, but in a way that appears to assume that the client is implementing its own retries.

I'm trying to figure out if use of this parameter requires me to put another layer of retries around the boto3 client call, or if supplying the param to boto3 will actually change the behavior of the internal retries.

This could maybe be fixed at the same time as #1412 , as they both relate to docs for FIFO queue usage.

**Comment by kyleknap** [comment]
Boto3 will not change the way it retries internally based on if the Id is provided. In general if you are using FIFO, I would recommend setting the `ReceiveRequestAttemptId` because if there is a network problem (e.g. connection error), `boto3` will always retry those types of problems and will retry with the parameters provided in the original request (i.e. it will reuse the same AttemptId from the original client call). I do not think it is necessary to put another level of retries on top of `boto3` unless there is an exception that you want retrying that `boto3` is not retrying for you. Hope this helps!

**Comment by sirosen** [comment]
That matches my team's understanding/expectation -- thank you for confirming.

I still think that the boto3 docs could be clearer on this subject.
If you _don't_ supply `ReceiveRequestAttemptId`, boto3 will still do its retries in the event of a network error, but because that parameter hasn't be supplied, it will also be missing from the retries.

The Developer Guide doc says
> it's a best practice to provide the receive request attempt ID and to retry with the same receive request attempt ID if the SDK operation fails.

Which is... something like 50% correct? You should provide it, but you shouldn't retry the call because the SDK in question, boto3, does that automatically.

And that would be okay, but I think the boto3 docs for this parameter actually make the situation _worse_ and more confusing:
> If a networking issue occurs after a ReceiveMessage action, and instead of a response you receive a generic error, you can retry the same action with an identical ReceiveRequestAttemptId to retrieve the same set of messages, even if their visibility timeout has not yet expired.

It sounds like the docs are instructing "you" (i.e. the user of boto3) to do retries with this parameter.
