### ISSUE TITLE
Add option to enable HTTP keep-alive

### ISSUE THREAD

**Issue by horike37** [boto/botocore#1677]
AFAIK, to enable HTTP keep-alive, you need to inject a custom header via the botocore event system.
https://github.com/boto/botocore/issues/902

However, it would be more user friendly if there is `http_keepalive` option to enable that.
What do you think? I will work on this if the botocore team thinks this is a reasonable approach.

**Comment by stealthycoin** [comment]
tcp_keepalive is already exposed. https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html?highlight=tcp_keepalive#configuration-file

**Comment by horike37** [comment]
Thank you for the response @stealthycoin 😄 
Yup, I know that option but that is to enable `TCP` keep alive. My suggestion is to enable `HTTP` keep alive.

**Comment by marcy-terui** [comment]
Hi @stealthycoin , Please let me add more information.

`botocore` isn't sending "Connection: keep-alive" in the HTTP request header. We will get the performance benefit by the header.
https://theburningmonk.com/2019/02/lambda-optimization-tip-enable-http-keep-alive/

**Comment by milancermak** [comment]
FWIW, you don't need to enable `Connection: keep-alive` to get the above mentioned performance benefit. I [wrote about why that is so](https://blog.milancermak.com/2019/03/08/dynamodb-nodejs-vs-python-and-persistent-connections/) TL;DR is that DynamoDB keeps the connection open, but NodeJS explicitly sets a `Connection: close` header.

Regardless, I find the event system to be sufficient to manipulate the headers:

```python
def set_connection_header(request, operation_name, **kwargs):
    request.headers['Connection'] = 'keep-alive'

ddb = boto3.client('dynamodb')
ddb.meta.events.register('request-created.dynamodb', set_connection_header)
```

**Comment by joguSD** [comment]
As @milancermak mentions connection reuse shouldn't be a problem, as it's [the default in HTTP/1.1](https://tools.ietf.org/html/rfc2616#section-8.1.2) and we use `urllib3`'s connection pooling. The related issue #902 was using a non-AWS product on localhost to serve an S3 compatible API which was closing the connection by default, which is why sending the header was helpful to them. Really, adding the header shouldn't be needed and if there is a case where it's required I think the event to inject the header is sufficient.

**Comment by vzf146** [comment]
https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#24630
