### ISSUE TITLE
Endpoints not being modeled as expected

### ISSUE THREAD

**Issue by buroa** [boto/botocore#1681]
Use boto3 to connect to sts or sqs. It will connect to sqs.amazonaws.com and sts.amazonaws.com... not sqs.us-east-1.amazonaws.com or sts.us-east-1.amazonaws.com. Regional endpoints have been implemented and the new AWS PrivateLink uses them.

**Comment by kyleknap** [comment]
For SQS and STS, I do not think we will be able to update the default endpoint for `us-east-1` for these services as changing them will introduce backwards incompatible changes. For SQS, some versions of Python can only connect with the `queue.amazonaws.com` endpoint. Then for STS, there is no guarantee that a user has deactivated support for that regional endpoint in their account. So if we switched to using the regional endpoint, it may all of a sudden make a user's call fail when they upgrade.

I think the best option would be to add a configuration like `use_regional_endpoints` to always force the regional endpoint is used for now. Thoughts?

Otherwise, the only way to really force the regional endpoint is used by setting the `endpoint_url`. For example:
```python
boto3.client('sqs', endpoint_url='https://sqs.us-east-1.amazonaws.com')
```

**Comment by fincd-aws** [comment]
"For backward compatibility, the AWS STS endpoints in the US East, AWS GovCloud (US), and China (Beijing) regions are always active and cannot be deactivated." [announcement](https://aws.amazon.com/about-aws/whats-new/2015/02/17/regional-endpoints-now-available-for-aws-security-token-service/)
So this would NOT be a breaking nor backwards-incompatible change for anyone - you are using sts.amazonaws.com now, which can be seamlessly replaced with sts.us-east-1.amazonaws.com which must be active in all accounts.
If region is specified for the call, just try that regions endpoint first, and fallback to us-east-1 if that fails and warn that the regional endpoint is disabled (disabling regional endpoints seems like a unique feature to STS).

STS now supported Private endpoints in us-west-2, but botocore still looks for sts.amazonaws.com, not sts.us-west-2.amazonaws.com, while all other services with private endpoints do work as expected (I didn't test sqs).

This is clearly a bug since all other services with regional endpoints behave correctly by looking up their regional endpoints directly (I needed 8+ other endpoints for EKS in a completely private VPC).

**Comment by cmckni3** [comment]
I have this issue as well. I tried using PrivateLink but noticed the lambda was timing out.

Things I noticed:

- Calls are made to `sqs.${dnssuffix}` instead of the regional endpoint
- `get_queue_by_name` returns a `Queue` with a URL of the form `queue.${dnssuffix}/${accountId}/${queueName}`

`aws-sdk-js` works as expected in a node.js lambda and the URLs come back in the form `sqs.${region}.${dnssuffix}/${accountId}/${queueName}`
