### ISSUE TITLE
urllib3 vendored library error

### ISSUE THREAD

**Issue by damian-sublime** [boto/botocore#1696]
The included library version has a markup error
I reported this initially to urllib3 repo but found that this is in fact vendored library loaded in botocore.
![Screen Shot 2019-03-12 at 10 51 13 AM](https://user-images.githubusercontent.com/6157074/54160569-c9166180-44b4-11e9-8e49-f94521df0d09.png)

The library throws an error in connectionpool.py
It's caused by the `\**` characters. This has been updated in source package to `\\**`
![Screen Shot 2019-03-12 at 10 52 11 AM](https://user-images.githubusercontent.com/6157074/54160708-21e5fa00-44b5-11e9-932a-79206f7aa86e.png)

Please de-link the old library

**Comment by kyleknap** [comment]
The vendored version of `urllib3` comes from our vendored version of `requests`. I agree we should remove the vendored versions of `requests`/`ullib3` especially since we no longer rely on them. I would recommend following this GitHub issue: https://github.com/boto/botocore/issues/1608 to track the removal of these vendored libraries. Closing this issue in favor of the linked one.
