### ISSUE TITLE
Multiple FIPS endpoints msising from botocore/data/endpoints.json

### ISSUE THREAD

**Issue by broosa** [boto/botocore#1697]
Currently botocore does not list any FIPS validated endpoints for multiple AWS services, including EC2, Route53, and S3. Per the list [here](https://aws.amazon.com/compliance/fips/), those services (and others) do indeed support access via FIPS validated endpoints.

This breaks some functionality in aws-cli as well when any the following regions are used:
- us-east-1-fips
- us-east-2-fips
- us-west-1-fips
- us-west-2-fips

I see from the commit logs that modifications to endpoints.json are committed from an automated system. Does this mean that any pull request I might submit would interfere with that?

Thanks,

@broosa

**Comment by kyleknap** [comment]
The endpoints are added via an automated system. We pull our `endpoints.json` from an internal upstream source so we would need to get the upstream source updated in order to pick these up. So any pull request sent to fix the `endpoint.json` file would be clobbered by our automated system. I will look into getting this updated from our side.

**Comment by kevinyas56** [comment]
Also seems applicable to FIPS regions for us-gov (i.e. fips-us-gov-west-1) ref: https://docs.aws.amazon.com/govcloud-us/latest/ug-west/using-govcloud-endpoints.html

**Comment by kdaily** [comment]
Confirmed that FIPS endpoints for these services are now in the endpoints file.
