### ISSUE TITLE
allow the use of urllib3 1.25.x

### ISSUE THREAD

**Issue by prometheanfire** [boto/botocore#1733]
please either uncap (preferred) or relax the cap on urllib3 in `setup.py` for urllib3.  botocore is currently the only library holding back the usage of urllib3-1.25 (requests just relaxed their cap).

**Comment by yan12125** [comment]
There's a pull request at https://github.com/boto/botocore/pull/1720 but no comment from boto devs yet.

**Comment by prometheanfire** [comment]
well, I guess we'll see if they do anything about this, not looking good though

**Comment by jamesls** [comment]
Taking a look now, assuming all the tests pass and there's no additional versions of python being dropped, we should be able to use the latest version.  I'll comment over in the linked PR.

**Comment by prometheanfire** [comment]
I ended up creating https://github.com/boto/botocore/pull/1735 a few days ago

**Comment by jamesls** [comment]
Yep, that's what I'm testing now.

**Comment by nateprewitt** [comment]
Hi @medley56, you can find the current tracking issue in https://github.com/boto/botocore/issues/2926. urllib3 2.0 is currently incompatible with a number of Amazon platforms including Amazon Linux and Lambda. We've left the pin in place to avoid unexpected breakages on new deployments in any of these ecosystems.

For the time being, we'd recommend pinning `urllib3<2` in your dependencies to be an explicit constraint. This should mirror what's already explicitly defined in botocore.

I am however surprised you're seeing backtracking, that should be resolved in modern versions of pip. If you wouldn't mind opening a new issue with a minimal example of how you're encountering this, we'd be happy to investigate further.

**Comment by medley56** [comment]
Gotcha. I'm opting to pin botocore to only the most recent ~50 releases and that has solved the dependency resolution for now. I also want the autoupdate when botocore does eventually support urllib3 v2. 

I'm actually using Poetry to do dependency resolution since it's reportedly more robust that pip and does a lot of other nice environment management and build tasks for me. It could be that Poetry's dependency solver is somehow pathologically slowed by this dependency specification structure (I notice that it actually has to download every botocore package version because presumably the metadata on PyPI is incomplete). But I can confirm that pinning either botocore or urllib3 fixes the issue.

So maybe there's another hidden request in here: add complete metadata to PyPI so that dependency solvers don't have to download the package itself from PyPI to inspect the dependencies.
