### ISSUE TITLE
Waiter for ssm to finish executing a command

### ISSUE THREAD

**Issue by dimzak** [boto/botocore#1744]
Use case:
After ssm [send_command](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ssm.html#SSM.Client.send_command) one has to wait until this command executes by running [get_command_invocation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ssm.html#SSM.Client.get_command_invocation) and wait for a result like `Failed`, `Success` etc.

A waiter for `"operation": "GetCommandInvocation"` would come very handy as it can wait until a command execution finishes.

P.S.
Already have this waiter ready for a PR if there is value in this enhancement :)

**Comment by JordonPhillips** [comment]
Feel free to open up that pr! We'll have to have some of the other sdk folks look at it to get it merged, but we can get that ball rolling.

**Comment by myniva** [comment]
I am looking for that functionality as well. If needed, I have the bandwidth to work on this. @JordonPhillips what actions are needed to get this rolling again?

**Comment by stobrien89** [comment]
Hi all,

Thanks again for the request. We are now submitting requests for paginators and waiters upstream so that all AWS SDKs benefit from a consistent implementation. I will pass on the request for these waiters to the service team. We will also update the guidance in the contributing guide to better reflect this policy. I've added an issue to track this here:

aws/aws-sdk#90

Thanks again for bringing this to our attention!
