### ISSUE TITLE
mturk documentation api link change

### ISSUE THREAD

**Issue by deargle** [boto/botocore#1746]
Links in the docs for mturk services to AWS API are broken. 

Current: `https://docs.aws.amazon.com/goto/WebAPI/mturk-requester-2017-01-17/DeleteQualificationType`

Should become: `https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_DeleteQualificationTypeOperation.html`

That is:
* api version name replaced by `latest` 
* operation name prefixed with `ApiReference_` and suffixed with `Operation.html`

etc.

I would submit a PR but I can't readily see where the api links are being sourced from.

**Comment by JordonPhillips** [comment]
Those goto links are deliberate - they separate the specifics of the service's doc structure and availability from the links we generate and place. The downside of this system is that the service team is responsible for hooking their side up, otherwise it falls back to the root landing page for aws docs. In this case it looks like the service team doesn't support them yet. I would recommend asking about it on [their forum](https://forums.aws.amazon.com/forum.jspa?forumID=11). I'll also contact them internally, but showing customer demand helps drive action.

**Comment by deargle** [comment]
I'll post there as soon as my forum account is "eligible" to post :sigh: -- then I'll link back here.

**Comment by jamesls** [comment]
Resolving in favor of forum link.

**Comment by deargle** [comment]
I think the mturk team fixed the links, anyhow
