### ISSUE TITLE
del self._deferred[name] is not try-excepted in ComponentLocator.get_component

### ISSUE THREAD

**Issue by wenduowang** [boto/botocore#1776]
Hi,
This issue is related to [#801](https://github.com/boto/boto3/issues/801)
`KeyError: 'endpoint_resolver'` does occur in multi-threads. However this particular error seems fixable from source.
Looking at [Line 906](https://github.com/boto/botocore/blob/develop/botocore/session.py#L906) ```del self._deferred[name]``` is not enclosed in try-except, while [Line 915](https://github.com/boto/botocore/blob/develop/botocore/session.py#L915) and [Line 922](https://github.com/boto/botocore/blob/develop/botocore/session.py#L915) are both protected.
Is there any reason for this design?
Comment on Line 903 says:
>            # Only delete the component from the deferred dict after
>            # successfully creating the object from the factory as well as
>            # injecting the instantiated value into the _components dict.
Does it mean that the entire ```get_component ``` method should be try-excepted as well?
Thanks!

**Comment by jamesls** [comment]
The main issue is that all of this client creation and component stuff isn't thread safe, so it'd still need a bit more work (and we'd likely need to add locking) in order to get this working the way we want.  For example, even if we protected against the `KeyError` you linked, it's possible that afterwards two threads each create their own component, register it with the session, and return it back to the caller.  So now you'd have two of the same components when there should really just be one, which could lead to even more subtle broken behavior.

I think if there's enough interest in this, we should make the whole component machinery thread safe.
