### ISSUE TITLE
botocore.utils:parse_timestamp negative timestamp causes UnhandledException

### ISSUE THREAD

**Issue by faxx1080** [boto/botocore#1783]
In botocore.utils:parse_timestamp (~Line 544), if a negative value is passed, a OSError is thrown up the stack. When using general boto functions (example: get_command_invocation), this causes parsing of the entire response to fail.

Potential workarounds: Returning a timestamp at the epoch in case of OSError, or returning None and updating upstream commands to not throw on None.

Unfortunately, it is difficult for me to get a live example of the failure, but I may be able to extract a raw JSON response that when formatted via botocore causes the failure in a few days.

**Comment by faxx1080** [comment]
I've done more research into the matter: an SSM api call is returning a value of -6.21355968E10 for a date, which should map to Jan 1, 0000 12 AM UTC.

In Linux, when parsed with EDT timezone, an OverflowError is generated - date value is out of range. However, if UTC is forced, then the 'correct' date is returned.

In Windows, the MSVC libraries indicate the standard time data types and localtime function don't work with times before Jan 1 1970 UTC. Python returns an OSError when a negative value is passed.

The fromtimestamp function is dependent on the OS time functions, which explains the OSError.

The reason I report this is because of the fail-fast behavior, where it seems the lowest possible date would be a more reasonable return, instead of throwing an uncaught exception.

**Comment by swetashre** [comment]
@faxx1080 - Thank you for your post. This issue occurs when the ssm ```describe_instance_patches``` returns negative timestamp. Service should not give negative timestamp in the response. I have already contacted the service team about the issue and According to them the negative timestamp is arising because some packages don't have installed time, then we use DateTimeOffset.Minvalue to initialize the installed time. But DateTimeOffset.Minvalue corresponds to 1/1/0001 12:00:00 AM +00:00 not Unix epoch time : 01/01/1970 00:00:00 hence the service treats this as negative timestamp.

We are tracking this issue under the GitHub issue https://github.com/boto/boto3/issues/2069. I am closing this issue and let's track the progress of the issue under the linked GitHub issue.
