### ISSUE TITLE
Vendor version of requests/urllib3 has collections Deprecations 

### ISSUE THREAD

**Issue by cooperlees** [boto/botocore#1826]
Using 3.7.3 and enabling `PYTHONWARNINGS=error` I found:
```
File "/private/var/folders/tc/hbwxh76j1hn6gqjd2n2sjn4j9k1glp/T/ptr_venv_83634/lib/python3.7/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "/opt/homebrew/bin/../Cellar/python37/3.7.3_2/bin/../Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__init__.py", line 52, in __getattr__
    DeprecationWarning, stacklevel=2)
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```

Code:
https://github.com/boto/botocore/blob/develop/botocore/vendored/requests/packages/urllib3/_collections.py#L1

Would a PR wrapping this be accepted or are there plans to move to a newer version of requests eventually? I think this is fixed there (didn't double check).

**Comment by swetashre** [comment]
@cooperlees - Thank you for your post. Botocore moved off of using the vendored requests a while ago, it's only kept in for backwards compatibility of certain exceptions. 

Currently botocore doesn't make any use of it but there is a warning added for customer that we are taking it away soon. This issue is related to botocore issue https://github.com/boto/botocore/issues/1615

**Comment by cooperlees** [comment]
Ahh - My search let me down. Thanks - Will be great to get rid of this so I can have my CI run looking for deprecation warnings moving forward!
