### ISSUE TITLE
ParamValidator parameter length validation does not match model

### ISSUE THREAD

**Issue by mattsb42-aws** [boto/botocore#1845]
While I was digging into an issue over on moto about validating parameter values (https://github.com/spulec/moto/issues/2426), it occurred to me that all of the information that I need is in the service model, and botocore is loading that already. I started out thinking that I would just use botocore to load the model and do the validation myself, but thinking more about it, I remembered that botocore does client-side parameter validation already, which should be getting triggered before anything in moto even runs (at least for mock mode; server mode might still require in-moto validation, but I would still prefer to single-source that).

When I started looking at the parameter validation code in `botocore.validate`, I found two issues:

## blobs

Parameter length is not validated at all for blobs.

https://github.com/boto/botocore/blob/4dab254f75f9548f765e69e2f2ca1dcc51077e35/botocore/validate.py#L241-L250

## everything else

For other primitive types, while min length is validated, max length is not.

https://github.com/boto/botocore/blob/8a9b18a3632120181eb186ad0685c208160a4a6a/botocore/validate.py#L70-L86

At first I thought this must be an oversight, but there are even tests that make sure that this validation is not happening.

https://github.com/boto/botocore/blob/4dab254f75f9548f765e69e2f2ca1dcc51077e35/tests/unit/test_validate.py#L315-L323

https://github.com/boto/botocore/blob/4dab254f75f9548f765e69e2f2ca1dcc51077e35/tests/unit/test_validate.py#L336-L344

## questions

Are these validation behaviors intentional?
If so, can we document that we do not validate these characteristics?

**Comment by swetashre** [comment]
Thank you for your post. We avoid doing a lot of client side validation to help ensure clients are forward compatible. For example  EC2 increased the length of the IDs and if we validated the length of instance ids then when the API started to return longer IDs the client would fail to round trip the id due to validation.

**Comment by mattsb42-aws** [comment]
Sure, but isn't that the whole point of the service model? If the service model specifies constraints, we should be able to reasonably assume that those constraints are accurate, no?

**Comment by swetashre** [comment]
For all primitive data type we are checking for the min value but for blobs we are not doing any parameter validation as it can be stream of data and it can be of gigabyte size. 

We are checking for min length because let's consider an example:
```
get bucketname/objectname
```
If someone wants to use this command with empty ```objectname``` then the command will be ```get bucketname/ ``` but as http request does not consider the slash so in this case request will be only ```get bucketname``` . And in this case the server will return bucket information not the object information.
