### ISSUE TITLE
ValueError: I/O operation on closed file when reading from s3 obj['Body']._raw_stream

### ISSUE THREAD

**Issue by darwinyip** [boto/botocore#1898]
Getting `ValueError: I/O operation on closed file.` when reading from s3 raw stream.

Example on how it is read:
```
obj = s3_client.get_object(Bucket=bucket, Key=key)
raw_stream = obj['Body']._raw_stream
text_stream = io.TextIOWrapper(raw_stream)
csv_reader = csv.reader(text_stream)
```

After reading from the csv_reader for about 2000 lines, the exception triggers.

This started happening after upgrading libraries:
botocore from `1.7.43` to `1.13.21`
boto3 from `1.4.7` to `1.10.14`

**Comment by darwinyip** [comment]
Further investigation leads to `boto3==1.9.152` being the last working version.

**Comment by darwinyip** [comment]
I pinpoint the breaking version to be `boto==1.8.0` which I believe it is related to
```
feature:urllib3: [botocore] The vendored version of requests and urllib3 are no longer being used and botocore now has a direct dependency on newer versions of upstream urllib3.
```

**Comment by swetashre** [comment]
Thank you for your post. Instead of using ```urllib3.response.HTTPResponse``` have you tried using 
```botocore.response.StreamingBody``` and see if that works for your case:
```python
import boto3
obj = s3_client.get_object(Bucket=bucket, Key=key)
itr = obj['Body'].iter_lines() 
for row in itr:
    print(row)
```
The ```iter_lines``` method is implemented using the [splitlines](https://docs.python.org/2/library/stdtypes.html#str.splitlines) method, which return the contents of each line, discarding the newlines in the process.
Here is the documentation on botocore StreamingBody
https://botocore.amazonaws.com/v1/documentation/api/latest/reference/response.html
