### ISSUE TITLE
valid HTTP responses without a reason phrase considered malformed

### ISSUE THREAD

**Issue by malaysf** [boto/botocore#1931]
`awsrequest.py` is too restrictive in parsing 100 Continue responses and rejects valid responses that do not have a reason phrase.

The [HTTP 1.1 RFC](https://tools.ietf.org/html/rfc2616#section-6.1) does not require the status line to contain a reason phrase, and defines the line as follows: 
```
Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF
Reason-Phrase  = *<TEXT, excluding CR, LF>
```

 `awsrequest.py` will reject valid responses such as: `HTTP/1.1 100 \r\n\r\n` or `HTTP/1.1 500 \r\n\r\n`

I will post a PR for this issue in a few minutes.

**Comment by swetashre** [comment]
@malaysf - Thank you for the post. Marking this as enhancement. It looks like the PR is approved and there is a comment in it. Let's track the progress of this issue under the linked PR.

**Comment by tim-finnigan** [comment]
Thanks for your patience here. I reopened this issue because it auto-closed and another issue (https://github.com/boto/botocore/issues/3149) was recently opened asking for an update. The reason why this issue and the corresponding PR (https://github.com/boto/botocore/pull/1932) will not be prioritized is because the requested behavior is outside of the standard behavior of Amazon S3.
