### ISSUE TITLE
OSError raised if called with 0.0 and different local timezone (UTC+1)

### ISSUE THREAD

**Issue by mbayrak78** [boto/botocore#1939]
Hello,

we catched an OSError on following line if called with 0.0 and timezone UTC+1:

https://github.com/boto/botocore/blob/d6b91089832c5dd14c84d2f00a12204cf5a2b187/botocore/utils.py#L607

The bug is in the summation:
0.0 + (-3600) => can't be converted from OS (windows) to an epoch time earlier than zero point.

BR

**Comment by swetashre** [comment]
@mbayrak78 - Thank you for your post. This looks to be an issue with an underlying library dateutil. I was able to find a related issue on their repository: https://github.com/dateutil/dateutil/issues/197. I am not sure if there is much we can do in boto3 to get around it.

These are some related github issue and stack overflow link which may help you to find a workaround : 
https://github.com/boto/boto3/issues/1238
https://stackoverflow.com/questions/38918668/dynamodb-create-table-calls-fails

**Comment by mbayrak78** [comment]
@swetashre, thanks for your reply.
As writtenin one of the links you provided, boto3 can patch utils.py as:
https://github.com/boto/boto3/issues/1238#issuecomment-413023250

With that you ensure that at least no date earlier than minimum is calculated (otherwise an OSError occour).

**Comment by Tobotimus** [comment]
> This looks to be an issue with an underlying library dateutil.

I disagree that this is a bug in dateutil. This is a bug in `botocore.utils.parse_timestamp`.

The `parse_timestamp` function naively makes use of the built-in `datetime.fromtimestamp()` classmethod despite the many warnings listed about the edge cases of that classmethod in its [documentation]((https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp)) (in particular, the warning about parsing timestamps outside of a platform-dependent range). I think the `parse_timestamp` function ought to use an alternative method to parse timestamps. This is especially necessary with regards to timestamps returned in API responses (which I gather are all relative to the Unix Epoch) whereas the `datetime.fromtimestamp` classmethod is intended for timestamps generated by the current platform, Unix or otherwise.

**Comment by jwilges** [comment]
> > This looks to be an issue with an underlying library dateutil.
> 
> I disagree that this is a bug in dateutil. This is a bug in `botocore.utils.parse_timestamp`.

@Tobotimus this could be a little of column A and a little of column B, but I believe there is a happy medium short term fix: patch `parse_timestamp` to conditionally use `tzwinlocal()` instead of `tzlocal()` on Windows, as that conditional behavior is what @pganssle proposed for a change to `gettz()` in `dateutil`:

> I think my preferred solution to the very real UX challenge you have identified, @h-vetinari, is to make tz.gettz() return tz.tzwinlocal instead of tz.tzlocal. In general, I think that tz.gettz is intended to get you the "right time zone object" for the job, and it may make sense to make tz.tzwinlocal the default "local time" on platforms where it's available.

See my pull request #1987 for an example of what I am suggesting. A change like this will make life a good deal less painful for Windows **botocore** users.

**Comment by nateprewitt** [comment]
Thanks to @jwilges for getting the ball rolling on this!

We've merged #1987 as an interim solution while dateutil/dateutil#197 remains unresolved. We'll now perform a best effort fallback to `tzwinlocal` if we fail to parse the timestamp on Windows. This will maintain backwards compatibility but provide a potential route to recovery for the failure users were previously experiencing.

**Comment by nateprewitt** [comment]
Resolving now that PR has shipped with botocore 1.15.18+.

**Comment by mbayrak78** [comment]
Thank you all for the support.

BR
