### ISSUE TITLE
Read several items from DynamoDB: error 'object has to attribute'

### ISSUE THREAD

**Issue by okyung** [boto/botocore#1945]
I want to  get several items from dynamoDB using .batchGetItem, but I receive error: 
  "errorMessage": "'dynamodb.ServiceResource' object has no attribute 'batchGetItem'",

import json
import boto3

dynamodb = boto3.resource('dynamodb')
table = dynamodb.Table('planets')  

def lambda_handler(event, context):
    response = dynamodb.batchGetItem(
        {RequestItems: {      
        Keys: [
        {
          key: {
            'id': '12'
          }
        },
        {
          key: {
            'id': '25'
          }
        }
      ],
      ConsistentRead: true
    }
    }
)
    print(response)
    return {
        'StatusCode':200,
        'body': response
    }

Anyone have a suggestion as to how to read several dynamoDB items? I am sure it is v. easy, but I am just a beginner...(

**Comment by swetashre** [comment]
@okyung - Thank you for your post. In stead of this ```response = dynamodb.batchGetItem()``` you have to use ```dynamodb.batch_get_item()``` . That's why you are getting the error. 

Here is the link to the documentation on how to use ```batch_get_item```:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.ServiceResource.batch_get_item

Hope it helps and please let me know if you have any questions.
