### ISSUE TITLE
AWS::SNS::Topic is missing in the list of AWS Config resource types

### ISSUE THREAD

**Issue by mikegrima** [boto/botocore#2010]
Hello!

AWS Config supports SNS Topics, but `AWS::SNS::Topic` is currently missing in the AWS Config service JSON as a supported resource type:

https://github.com/boto/botocore/blob/develop/botocore/data/config/2014-11-12/service-2.json#L5972

**Comment by swetashre** [comment]
@mikegrima - Thank you for your post. This file comes from upstream. I will let the service team know about the issue. 

This change was introduced [here](https://aws.amazon.com/about-aws/whats-new/2020/03/aws-config-support-for-amazon-sns-now-available-in-aws-commercial-and-govcloud-regions/). I believe because this change is introduced this month, it is missing in the file. I will let the service team know about the issue.

**Comment by mikegrima** [comment]
Thank you @swetashre !

**Comment by mikegrima** [comment]
Hello! Any updates?

**Comment by swetashre** [comment]
It got added in today's release here
https://github.com/boto/botocore/blob/develop/botocore/data/config/2014-11-12/service-2.json#L6076

**Comment by mikegrima** [comment]
Excellent!
