### ISSUE TITLE
run_instances does not work with ValidUntil parameter when SpotInstanceType is one-time for SpotOptions

### ISSUE THREAD

**Issue by juhi-09** [boto/botocore#2021]
As per document of boto3 for run_instances API :

> ValidUntil (datetime) --
> The end date of the request. For a one-time request, the request remains active until all instances launch, the request is canceled, or this date is reached. If the request is persistent, it remains active until it is canceled or this date and time is reached. The default end date is 7 days from the current date.

However, when I make a 'one-time' request, following error is thrown:
`ClientError: An error occurred (InvalidParameterCombination) when calling the RunInstances operation: The parameter validUntil cannot be specified when the SpotRequestType is set to 'one-time.`

**Comment by swetashre** [comment]
@juhi-09 - Thank you for your post. A one-time Spot Instance request remains active until Amazon EC2 launches the Spot Instance, the request expires, or you cancel the request. If the Spot price exceeds your maximum price or capacity is not available, your Spot Instance is terminated and the Spot Instance request is closed.

I believe with one-time spot instance request the validUntil is already defined and you can not specify it. Have you tried the calling the api without specifying validUntil parameter ?

I agree documentation is not clear on this part. As boto3 documentation is generated from the API reference, i will let the service team know about the issue.

**Comment by swetashre** [comment]
Looks like the documentation is updated. 
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.run_instances

ValidUntil (datetime) --

The end date of the request, in UTC format (YYYY -MM -DD T*HH* :MM :SS Z). Supported only for persistent requests.

-   For a persistent request, the request remains active until the ValidUntil date and time is reached. Otherwise, the request remains active until you cancel it.

-   For a one-time request, ValidUntil is not supported. The request remains active until all instances launch or you cancel the request.


I am closing the issue as it has been resolved.
