### ISSUE TITLE
AssumeRoleCredentialFetcher doesn't allow to specify regionalized STS endpoint

### ISSUE THREAD

**Issue by mihirsoni** [boto/botocore#2124]
**Describe the bug**
Leveraging Custom AssumeRoleProvider and using `AssumeRoleCredentialFetcher` doesn't allow to use regionalized STS endpoint.

**Expected behavior**
A config should be allowed to taken so that consumer can pass STS regionalized endpoint or global based on need.

https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L820-L828

**Comment by zdutta** [comment]
@mihirsoni - Thank you for the post. AssumeRoleProvider and AssumeRoleCredentialFetcher aren't considered public interfaces and should be avoided since they may break without warning. Furthermore, the configuration data that is handled by those classes are “credentials” configuration data while region is considered “non-credentials”. Documentation that explains this distinction can be found at: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials. 
You can get the same outcome by using IAM role configuration in order to specify either regionalized or global endpoints for STS. The steps for configuration via the aws cli are here at https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html. Additional documentation explains using the ~/.aws/config configuration file or environment variables for setting STS regional endpoints. Resource can be found at: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-a-configuration-file and https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables.

**Comment by mihirsoni** [comment]
Hi @zdutta 
Thanks for letting me know. Ideally the use case is to write custom credentials fetcher, I don't think solution you provided would work for that use cases.

Basically use case is from EC2 IP credentials assume role which can refresh credentials on given refresh interval.

**Comment by zdutta** [comment]
If you’re using a profile you can set the sts_regional_endpoints configuration in order to configure STS clients to use regional endpoints (including the one used by the AssumeRoleCredentialFetcher):

```
[profile myprofile]
sts_regional_endpoints = regional
```

If your custom provider isn’t using a profiles/config file, you can set this in the environment and in all STS clients that are instantiated :
```
AWS_STS_REGIONAL_ENDPOINTS=regional
```
