### ISSUE TITLE
AWS Amplify Apps might not have description

### ISSUE THREAD

**Issue by outcoldman** [boto/botocore#2299]
**Describe the bug**
All my AWS Amplify Apps are created with the Web Console. There is no way to supply or enter description on any steps. So all my apps have description = null. 

I see that in the service definition description is required https://github.com/boto/botocore/blob/develop/botocore/data/amplify/2017-07-25/service-2.json#L642

And it is also required in the documentation https://docs.aws.amazon.com/amplify/latest/APIReference/API_App.html

Both are incorrect. 

I noticed this bug at first with the Swift Soto package (unofficial AWS library for Swift) https://github.com/soto-project/soto/issues/474, which I believe copies or autogenerate the code from botocore definitions. 

```
$ aws amplify list-apps | jq '.apps | .[] | {name: .name, description: .description}'
{
  "name": "whichmacshouldibuy",
  "description": null
}
{
  "name": "loshadki-web",
  "description": null
}
```

**Comment by zdutta** [comment]
Thank you for your post @outcoldman. I can see your source of confusion. The documentation to which you pointed to is for the [App data type](https://docs.aws.amazon.com/amplify/latest/APIReference/API_App.html). That is also what is being pointed to in the service definition member. This field is required for the App object; however not required for creating an App. Documentation for this operation (CreateApp) can be found [here](https://docs.aws.amazon.com/amplify/latest/APIReference/API_CreateApp.html). 
Going back to the issue at hand, it seems that since you are not being prompted to create a description through the web console, it is being defaulted to `null`. I will mark this as a feature request and forward this on to the service team. Will post here when I get any update.
