### ISSUE TITLE
Typo in BOTOCORE_DEFAUT_SESSION_VARIABLES variable name

### ISSUE THREAD

**Issue by adamantoise** [boto/botocore#2361]
**Describe the bug**
In `botocore/configprovider.py`, the variable name `BOTOCORE_DEFAUT_SESSION_VARIABLES` contains a typo: the word `DEFAUT` should be spelled `DEFAULT`.

**Comment by stobrien89** [comment]
Hi @adamantoise,

Thanks for the heads-up!

**Comment by nateprewitt** [comment]
Hi @adamantoise,

Thanks for reaching out! We're aware of the typo in the variable, but unfortunately, fixing it isn't straight forward. Due to the age of the variable, it's difficult to know what downstream systems may be relying on this particular spelling. Any update would be a breaking change. We could rename the variable and create an alias for the old spelling, but this means users will still get incorrect suggestions in their IDE prompts etc.

For that reason, we haven't really touched it because the options available don't provide a lot of value. That's the conclusion we reached last time this was discussed at least, but please let us know if you have further thoughts.

**Comment by adamantoise** [comment]
No problem if you want to close this as WONTFIX, it's obviously very minor and inconsequential.  It's certainly not worth putting in a lot of effort to fix.  (You could optionally add a comment explaining the unfortunate name if you'd like.)

**Comment by nateprewitt** [comment]
Yeah, I think a brief comment callout is a reasonable suggestion. We'll leave this open to track that as a quick follow up item. Thanks again for reviving the conversation.

**Comment by adamantoise** [comment]
This issue is still present (but, again, of little consequence).  I'd prefer it though if a _human_ closed this rather than a bot, if the decision is not to fix it.

**Comment by nateprewitt** [comment]
This was resolved in #3029, we should be set to close this now.
