### ISSUE TITLE
botocore/credentials.py: Fallback to looking for custom process if token in shared credentials file is expired

### ISSUE THREAD

**Issue by MattJaccino** [boto/botocore#2427]
**Is your feature request related to a problem? Please describe.**
AWS CLI is set up such that, "If there are credentials in both files for a profile sharing the same name, the keys in the credentials file take precedence."  However, if the token found in that file is expired, it complains and exits instead of continuing the search and looking for a custom process.

Context:
My company created an external process to produce temporary credentials to use AWS CLI.
Users typically name the profiles after the role, so as to be easy to remember.
The credentials are deposited into /.aws/credentials under this same name occasionally, so lookup is fast.
If a user specifies a profile, '--profile <PROFILE>', and there is both a profile in /config and an entry in /credentials called <PROFILE>, AWSCLI, through it's credentials process in botocore, checks the /credentials file first.
This makes sense, however if the token found in /credentials is invalid, botocore doesn't check for a custom process to get a fresh one.

**Describe the solution you'd like**
If botocore's search for credentials in the shared credentials file fails, it should look for a custom process in /config for the given profile.

**Comment by stobrien89** [comment]
Hi @MattJaccino,

Thanks for the feature request!

**Comment by stobrien89** [comment]
Hi again @MattJaccino,

Thanks again for the request.  I chatted with the team a about this and the consensus is that we wouldn't introduce a change like this due to the lack of backwards compatibility, and this being a change that would essentially have us break parity with the established [precedence and credential provider order](https://docs.aws.amazon.com/sdkref/latest/guide/creds-config-files.html#overview-cred-provider-order) that is shared amongst other tools and SDKs.
