### ISSUE TITLE
Service Definition(s3): Size defined to be type integer but is actually long

### ISSUE THREAD

**Issue by endgame** [boto/botocore#2509]
In the service definition for S3, the `Size` shape (used for object sizes) is marked `integer`:

https://github.com/boto/botocore/blob/879726e46b210cecb8f945e1448c2e860b3d4298/botocore/data/s3/2006-03-01/service-2.json#L8960

But other shapes that describe byte counts are marked `long`:

https://github.com/boto/botocore/blob/879726e46b210cecb8f945e1448c2e860b3d4298/botocore/data/s3/2006-03-01/service-2.json#L1430-L1432

**Comment by kdaily** [comment]
Hi @endgame,

Thanks for your post. The models present in botocore are defined upstream by the service teams, in this case the S3 service team. As you note here, they are not related to each other in the model - `BytesProcessed` is not modeled as a `Size` attribute.

You didn't indicate why this would be an issue, but if you have a specific question on the implementation or for general issues regarding the S3 service, I would suggest asking in the AWS Forums where an S3 engineer can directly address your concerns.

https://forums.aws.amazon.com/forum.jspa?forumID=24&start=0

Since this is not an issue with the Python SDK's implementation of the S3 API, I'll close this issue.

**Comment by endgame** [comment]
Hi @kdaily, we use these models to generate code in `amazonka`, an unofficial Haskell SDK for AWS, and the fewer fixups and patches that we have to apply to them to do so, the better for us and everyone else who has to consume them. In our mappings, `int` gets mapped to machine integers and `long` to arbitrary-precision integers, so on 32bit architectures an `int` object size overflows when describing large S3 objects.

See also #2508 , which handled a related issue in autoscaling by passing upstream to the service team.

**Comment by kdaily** [comment]
Hi @endgame,

Thanks for the clarification. When something is errantly marked as required (as in #2508) that would require a service team fix. For this one, the API is defined by the service team as well but it is working as expected; this would be a feature request at best, but would probably be considered a breaking change. 

With these details, I can pass along the feedback that this poses an issue for you!
