### ISSUE TITLE
Unused threading.Lock() in Endpoint class

### ISSUE THREAD

**Issue by oort7** [boto/botocore#2569]
**Describe the bug**
Endpoint class [creates](https://github.com/boto/botocore/blob/master/botocore/endpoint.py#L88) `threading.Lock()` but does not use it anywhere.

I'm not sure if it is necessary or not but I've found it while debugging issue in my code where boto3 client hangs and the last log is `Sending http request: (...)` from Endpoint class.

**Comment by nateprewitt** [comment]
Hi @oort7,

This was removed as part of a larger refactoring in 2015 (#414) because we no longer needed locking constraints to perform signing. The class attribute was left in place for backwards compatibility if anyone was subclassing/extending this. We don't want to remove it for those reasons, but it doesn't have a strong purpose currently.

The client hanging on Sending request is more likely to be around http timeouts or incomplete/long running responses. We'd be happy to work through that problem with you if you'd like to open a new ticket with logs.

If you have any more questions/comments about the lock specifically, please let us know. Thanks!

**Comment by oort7** [comment]
Hi @nateprewitt,
Thank you for the explanation. It seems that my issue is indeed related to default boto timeouts being longer than default API Gateway timeout.
