### ISSUE TITLE
Service Definition(s3, glacier): Mark UploadId as required when creating multipart uploads?

### ISSUE THREAD

**Issue by endgame** [boto/botocore#2572]
Filing a combined issue because the services are extremely similar.

I help maintain `amazonka`, a Haskell AWS SDK that uses botocore definitions. One of our users queried whether creating a multipart upload can ever successfully return but not provide an upload ID. The service definitions ([s3](https://github.com/boto/botocore/blob/b943471b01097d53b94a991c5771996a7688a08d/botocore/data/s3/2006-03-01/service-2.json#L2210), [glacier](https://github.com/boto/botocore/blob/b943471b01097d53b94a991c5771996a7688a08d/botocore/data/glacier/2012-06-01/service-2.json#L1511)) do not mark this field as required, but it's heavily implied to always exist from other documentation:

* S3: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/InitiateMultipartUploadResult.html#getUploadId--

   > Contains the results of initiating a multipart upload, particularly the unique ID of the new multipart upload.

* Glacier: https://docs.aws.amazon.com/amazonglacier/latest/dev/api-multipart-initiate-upload.html

   > Amazon S3 Glacier (S3 Glacier) creates a multipart upload resource and returns its ID in the response.

I don't think there's anything botocore can do to fix these directly unless you maintain your own patches for service definitions. But perhaps these can get passed up to service teams and maybe updated definitions will trickle down?

**Comment by stobrien89** [comment]
Hi @endgame,

Thanks for reaching out!  I actually had a [similar question](https://github.com/aws/aws-cli/issues/6311#issuecomment-915340962) come up earlier this year regarding S3 documentation marking `CreationDate` as optional output for a `Bucket` shape. While they agreed that a `Bucket` shape will never be returned without a `Name` (also listed as optional) or `CreationDate` S3's stance on seemingly required output fields is to mark them as optional, as output is something the user cannot control.  I did inquire about changing them since it seemed to cause some confusion, but they declined to do so.
