### ISSUE TITLE
KMS service definition: `SignResult` wrapper is not used

### ISSUE THREAD

**Issue by zbaylin** [boto/botocore#2576]
**Describe the bug**
The result of the `sign` operation is wrapped in a field called `SignResult`, but this is not specified as a `resultWrapper` in `kms/2014-11-01/service-2.json`:

https://github.com/boto/botocore/blob/3b7a7b329eada78d1026095a09c9928d3c491e37/botocore/data/kms/2014-11-01/service-2.json#L745-L752

**Use elsewhere**
Amazon's AWS SDKs have a `SignResult` model, taking the Android one as an example:
https://github.com/aws-amplify/aws-sdk-android/blob/d4116c1909f1ecb5a31edf8588882a6181b73deb/aws-android-sdk-kms/src/main/java/com/amazonaws/services/kms/AWSKMSClient.java#L5660-L5687

This should be an easy fix, let me know if I can just open a PR for it or if there's more that needs to be done.

Thanks!

**Comment by stobrien89** [comment]
Hi @zbaylin,

Thanks for reaching out! The service models we use are defined at the service level, meaning they are written/maintained by service teams and pushed to the (standard(non-amplify): Python, JavaScript, Go, CLI, etc.) AWS SDKs and tools.  We unfortunately cannot accept external contributions to the models since they would be overwritten by the automated process that pushes this code from the service teams.

As for the `resultWrapper` key itself,  it's really up to the service that writes the model as to whether or not they want to include specific elements. My guess would be that there's a particular reason they excluded it from the SDK models (I don't see it anywhere else in their model), but I can try to find out why if you'd like!

**Comment by zbaylin** [comment]
Hi @stobrien89,

Thanks for the quick response. 

> We unfortunately cannot accept external contributions to the models since they would be overwritten by the automated process that pushes this code from the service teams.

Bummer, but that makes sense.

> My guess would be that there's a particular reason they excluded it from the SDK models (I don't see it anywhere else in their model), but I can try to find out why if you'd like!

That would be great if possible, but no worries if not/rush! In the meantime I can just override the key myself in my project.

Thanks again!

**Comment by stobrien89** [comment]
@zbaylin,

No problem! I did want to double-check where you're seeing the key and which SDK/tool you're using— I didn't see the key present in a sample call from the CLI or Boto3(both of which use botocore as the low-level library).  A sample response (with any sensitive information redacted) would also be great.

**Comment by stobrien89** [comment]
Hi @zbaylin,

Thanks for the confirmation.  I thought you were probably working with the raw response, but just wanted to be sure.  The KMS team would have likely requested this information as well.  

I've created an internal ticket to inquire about this and will let you know as soon as I have an update!

**Comment by stobrien89** [comment]
V487833764

**Comment by zbaylin** [comment]
@stobrien89 Thanks!

I actually realized that this is more broad than just `Sign`. I think every KMS operation is "wrapped" like this:

`ListKeys`:
```
<ListKeysResponse xmlns="https://trent.amazonaws.com/doc/2014-11-01/">
  <ListKeysResult>
    <KeyCount>1</KeyCount>
    <Keys>
      <member>
        [redacted]
      </member>
    </Keys>
    <Truncated>false</Truncated>
  </ListKeysResult>
  <ResponseMetadata>
    <RequestId>[redacted]</RequestId>
  </ResponseMetadata>
</ListKeysResponse>
```

**Comment by stobrien89** [comment]
Hi again @zbaylin,

Sorry for the lack of updates!  

I was able to get in touch with someone more familiar with the modeling and they mentioned that the lack of the `ResultWrapper` is due to the fact that KMS uses [JSON RPC protocol with version `1.1`](https://github.com/boto/botocore/blob/3b7a7b329eada78d1026095a09c9928d3c491e37/botocore/data/kms/2014-11-01/service-2.json#L6-L7), which does not use `ResultWrapper`.  More information on AWS protocols can be found [here](https://awslabs.github.io/smithy/1.0/spec/aws/index.html#aws-protocols).

They did add that since you don't seem to use similar protocols in the `aws-ocaml` models, you should be free to do as you wish.  Hope this helps!
