### ISSUE TITLE
[doc] SSM: get_parameters_by_path has a typo

### ISSUE THREAD

**Issue by bblommers** [boto/botocore#2582]
https://github.com/boto/botocore/blob/63107d6f1fbf8a53b23dbf19f49ff849501c8ffd/botocore/data/ssm/2014-11-06/service-2.json#L7962

The explanation of the Path-parameter contains the word `succeed` with three e's:

> For the API call to succeeed, the last part ...
>

**Comment by stobrien89** [comment]
Hi @bblommers,

Thanks for pointing this out!  The SDK docs are largely derived from the [service API docs](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParametersByPath.html#API_GetParametersByPath_RequestSyntax) upstream and I'm seeing this in the [JS SDK docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SSM.html#getParametersByPath-property), as well so this is something I'll need to contact the SSM team about.  

Because this is an issue that impacts multiple SDKs, I've created a [new issue](https://github.com/aws/aws-sdk/issues/149) in our shared SDKs repository for tracking.  I'll let you know as soon as I have an update!
