### ISSUE TITLE
Add resource waiter to Lambda for Function Active or Inactive

### ISSUE THREAD

**Issue by anjo-swe** [boto/botocore#2584]
**Is your feature request related to a problem? Please describe.**

Before updating a lambda you need to confirm that its State is `Active` or `Inactive`

> **NOTE:** Functions can only be updated if they are in the Active or Inactive state. Update commands issued against functions that aren’t in the Active or Inactive state will fail before execution.

**Reference:** https://aws.amazon.com/blogs/compute/tracking-the-state-of-lambda-functions/

**Describe the solution you'd like**

Add a new waiter to https://github.com/boto/botocore/blob/develop/botocore/data/lambda/2015-03-31/waiters-2.json that is similar to `FunctionActive`

##### Example

```
    "FunctionActiveOrInactive": {
      "delay": 5,
      "maxAttempts": 60,
      "operation": "GetFunctionConfiguration",
      "description": "Waits for the function's State to be Active or Inactive.",
      "acceptors": [
        {
          "state": "success",
          "matcher": "path",
          "argument": "State",
          "expected": "Active"
        },
        {
          "state": "success",
          "matcher": "path",
          "argument": "State",
          "expected": "Inactive"
        },
        {
          "state": "failure",
          "matcher": "path",
          "argument": "State",
          "expected": "Failed"
        },
        {
          "state": "retry",
          "matcher": "path",
          "argument": "State",
          "expected": "Pending"
        }
      ]
    }
```

**Comment by tim-finnigan** [comment]
Hi @anjo-swe, thanks for reaching out. Waiters generally follow the pattern of waiting for one specific state rather than two. But I can see the reasoning behind this use case. I’ll reach out to the Lambda team to get their thoughts and let you know when I hear back.

Since this request would apply across SDKs, I’m transferring this to our [aws-sdk repo](https://github.com/aws/aws-sdk/issues). Here is the new issue I created: https://github.com/aws/aws-sdk/issues/155. Please refer to that issue for updates going forward.
