### ISSUE TITLE
UPDATE_COMPLETE is missing as possible terminal failure state for CFN StackDeleteComplete waiter

### ISSUE THREAD

**Issue by mariellanalepa** [boto/botocore#2590]
**Problem description**
Inspecting botocore/botocore/data/cloudformation/2010-05-15-waiters-2.json: 
Currently the CloudFormation waiter for “StackDeleteComplete” does not have an acceptor defined for stack status “UPDATE_COMPLETE” (“state”: “failure”). 
I have a situation where stack state on a failed DeleteStack action transitions from ‘DELETE_IN_PROGRESS’ to ‘UPDATE_COMPLETE’. The waiter in this case will timeout on max attempts after 60 min rather than recognizing this stack state as a terminal failure state and returning a WaiterError promptly. 

**Desired solution**
I would like “UPDATE_COMPLETE” to be included as a terminal failure state for the “StackDeleteComplete” waiter.

**Comment by kdaily** [comment]
Hi @mariellanalepa,

Thanks for the request. Changes to waiters are handled by the service team - we get the models for the waiters from them so that all AWS SDKs have the same behavior. I'll give this feedback to the CloudFormation team.

Can you describe the scenario where you get this state transition (`DELETE_IN_PROGRESS` to `UPDATE_COMPLETE`)?

**Comment by mariellanalepa** [comment]
I’m seeing it when I try to delete a stack in which there is an output/export in use by another stack (screenshot attached). I am not sure why in fact this is resulting in UPDATE_COMPLETE. Perhaps that is what should be updated rather than the waiter model. 
![Screen Shot 2022-01-17 at 12 52 37 PM](https://user-images.githubusercontent.com/47364601/149830638-d2968ba6-ccaf-405e-8a36-5edc099a0ecb.png)

**Comment by tim-finnigan** [comment]
Since updates to waiters are handles by service teams as mentioned earlier, I'm going to close this issue in favor of tracking here in our cross-SDK repository: https://github.com/aws/aws-sdk/issues/424. I reached out to the CloudFormation team for feedback and will update that issue when we hear back. Thanks!
