### ISSUE TITLE
[s3] Two region names are missing in S3 `BucketLocationConstraint`

### ISSUE THREAD

**Issue by vemel** [boto/botocore#2648]
You can see that `ap-southeast-3` and `us-east-1` are missing in S3 schema: https://github.com/boto/botocore/blob/develop/botocore/data/s3/2006-03-01/service-2.json#L1467

However, S3 service supports both `ap-southeast-3` and `us-east-1` regions. Also `EU` region probably has to be removed from the schema.

**Comment by tim-finnigan** [comment]
Thanks for reporting this @vemel. As mentioned [here](https://github.com/boto/botocore/pull/2649#issuecomment-1081059823) these changes would need to be made by the S3 team directly. I created an issue here in our cross-SDK repository since this affects other SDKs: https://github.com/aws/aws-sdk/issues/217

I reached out to the S3 team and will post an update there when I hear back.
