### ISSUE TITLE
Missing waiter for Sagemaker DescribeCompilationJob

### ISSUE THREAD

**Issue by scribu** [boto/botocore#2758]
### Describe the bug

The Sagemaker client has a `describe_compilation_job()` method, so I would expect there to be a waiter for it.

### Expected Behavior

The waiter exists and can be used

### Current Behavior

```
ValueError: Waiter does not exist: compilation_job_completed_or_stopped
```

### Reproduction Steps

```
import boto3
client = boto3.client("sagemaker")
waiter = client.get_waiter("compilation_job_completed_or_stopped")
```

### SDK version used

1.27.69

### Environment details (OS name and version, etc.)

Python 3.8

**Comment by tim-finnigan** [comment]
Thanks @scribu for reaching out. Your request seems consistent with these similar waiters currently available:
- [SageMaker.Waiter.ProcessingJobCompletedOrStopped](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Waiter.ProcessingJobCompletedOrStopped)
- [SageMaker.Waiter.TrainingJobCompletedOrStopped](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Waiter.TrainingJobCompletedOrStopped)
- [SageMaker.Waiter.TransformJobCompletedOrStopped](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Waiter.TransformJobCompletedOrStopped)

Since waiter models are shared across SDKs, I created a new issue for this here in our cross-SDK repository: https://github.com/aws/aws-sdk/issues/346. Service teams implement their own waiters, so I reached out to the Sagemaker team to see if they will consider this feature request. I'll update that new issue when I hear back. Thanks!
