### ISSUE TITLE
Textract / analyze-document / Document parameter has inaccurate documentation

### ISSUE THREAD

**Issue by jggoyder** [boto/botocore#2760]
### Describe the issue

The public facing Boto3 documentation for the Amazon Textract service give the following description for the Document / Bytes parameter:

> **Bytes** (bytes) --
> A blob of base64-encoded document bytes. The maximum size of a document that's provided in a blob of bytes is 5 MB. The document bytes must be in PNG or JPEG format.

This description is incorrect. As per the [API documentation](https://docs.aws.amazon.com/textract/latest/dg/API_AnalyzeDocument.html), the document bytes can be PNG, JPEG, PDF, or TIFF.

This inaccuracy has been the cause of wasted time in unnecessarily building additional functionality to process PDF documents.

---

Suggest replacing description with:

> **Bytes** (bytes) --
> A blob of base64-encoded document bytes. The maximum size of a document that's provided in a blob of bytes is 5 MB. The document bytes must be in **PNG, JPEG, PDF, or TIFF format.**

### Links

https://github.com/boto/botocore/blob/develop/botocore/data/textract/2018-06-27/service-2.json#L512

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/textract.html#Textract.Client.analyze_document

**Comment by tim-finnigan** [comment]
Hi @jggoyder  thanks for reaching out. Since this relates to the upstream [Document](https://docs.aws.amazon.com/textract/latest/dg/API_Document.html) API which is used across SDKs, I created an issue for this in our shared SDK repository: https://github.com/aws/aws-sdk/issues/349.

I also reached out to the Textract team regarding the documentation update. Please refer to that new GitHub issue for updates on this going forward. Thanks!
