### ISSUE TITLE
Support querying guardduty of partition 'aws-cn' in session

### ISSUE THREAD

**Issue by Zpa48** [boto/botocore#2786]
### Describe the bug

cn-north-1 and cn-northwest-1 regions are not available when querying regions for service 'guardduty' for 'aws-cn':

```python
>>> import botocore.session
>>> session = botocore.session.Session(profile = 'default')
>>> session.get_available_partitions()
['aws', 'aws-cn', 'aws-us-gov', 'aws-iso', 'aws-iso-b']
>>> session.get_available_regions('guardduty', 'aws-cn')
[]
>>> session.get_available_regions('guardduty', 'aws')
['ap-east-1', 'ap-northeast-1', 'ap-northeast-2', 'ap-south-1', 'ap-southeast-1', 'ap-southeast-2', 'ca-central-1', 'eu-central-1', 'eu-north-1', 'eu-west-1', 'eu-west-2', 'eu-west-3', 'me-south-1', 'sa-east-1', 'us-east-1', 'us-east-2', 'us-west-1', 'us-west-2']
```

### Expected Behavior

```python
session.get_available_regions('guardduty', 'aws-cn')
['cn-north-1', 'cn-northwest-1']
```

### Current Behavior

```python
session.get_available_regions('guardduty', 'aws-cn')
[]
```

### Reproduction Steps

session.get_available_regions('guardduty', 'aws-cn')

### SDK version used

-

### Environment details (OS name and version, etc.)

python3.6, boto3==1.11.9 botocore==1.14.9

**Comment by tim-finnigan** [comment]
Hi @Zpa48 thanks for reaching out. It looks like you're using a very old version of boto3, but even with a newer version the response may not be up to date. 

We have a tracking issue related to this: https://github.com/aws/aws-sdk/issues/206. I will follow up there and try to find out what needs to happen in order to fix this. Please let us know if you had any further questions and refer to that issue for updates going forward.
