### ISSUE TITLE
Document STS credential refresh functionality

### ISSUE THREAD

**Issue by littleidiot40** [boto/botocore#2837]
### Describe the issue

NASA EOSDIS' Earthdata Cloud platform store data in S3 but has requirements that limit access via usage of the AWS Secure Token Service. There is a use case where our users require long term access to S3 buckets but are limited by the 1 hour token expiration we employ. 

Large scale processing of large amounts of data are complicated by the need for credential management.

We discovered that there is an undocumented feature of the of boto core credentials.py that allow users to automatically refresh their credentials. Namely,

[create_from_metadata](https://github.com/boto/botocore/blob/e8155d6005a878b86bfdcd2823b41f7e2d6cde08/botocore/credentials.py#L444)

Which can be used to autorefresh credentials without user intervention once set up. Such a use case is demonstrated here
[Auto refresh tokens for S3 access](https://github.com/nasa-esdswg-ml/edc-notebooks/blob/main/s3-access-beyond-one-hour.ipynb)

NASA EOSDIS are reluctant to promote this solution since it relies on code that is undocumented and may be subject to deprecation without notice. If this feature was documented we would be able to promote it as a viable solution to the above use case.

### Links

https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html

**Comment by tim-finnigan** [comment]
Hi @littleidiot40 thanks for reaching out. We don't recommend relying on undocumented behavior as we can't guarantee long-term support of this functionality. But this issue does seem to overlap with a couple of others in the boto3 repository: https://github.com/boto/boto3/issues/443 and https://github.com/boto/boto3/issues/2345. 

We brought this up recently for team discussion and the current thinking is that feature requests involving credentials should be considered at the cross-SDK level rather than by an individual SDK team. And we should also check with the IAM team to see if anything is planned on the service side related to this. 

Some further review is needed in order to determine next steps and escalation but I recommend referring to those issues for updates going forward. And you can always consider opening a case through [AWS Support](https://aws.amazon.com/contact-us/) for more direct assistance.
