### ISSUE TITLE
Vulneribility detected

### ISSUE THREAD

**Issue by haassto** [boto/botocore#2838]
### Describe the bug

We are currently using boto3 version 1.26.30. We are using NexusIq which scans all our dependencies and at the moment it fails for 
botocore 1.29.30 with a high security warning

Vulneritiblity [CVE-2022-23491](https://nvd.nist.gov/vuln/detail/CVE-2022-23491)

### Expected Behavior

CVE-2022-23491 is not detected anymore

### Current Behavior

CVE-2022-23491 detected

### Reproduction Steps

CVE-2022-23491

### Possible Solution

I'm not an expert here, but it could probably solved with updating certif:
https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8

### SDK version used

1.26.30

### Environment details (OS name and version, etc.)

Linux

**Comment by lorienpatt** [comment]
Also hitting this issue.. it is flagged in the National Vulnerability Database.

**Comment by tim-finnigan** [comment]
Thanks for reporting this - this issue was also being tracked internally and I wanted to get some more information before following up here. I was advised to share the following:

1. Installing `certifi` supersedes anything in Botocore, this is the best general way to keep your certificates up to date, so we recommend that you keep your version of `certifi` up to date.
2. Boto3 only communicates with AWS services which do not use third-party certs unless explicitly redirected by the customer. The default usage of Boto3 is not subject to this CVE.
3. Customers can also set their cert to with `AWS_CA_BUNDLE` in their environment vars or `ca_bundle` in the Config if they need finer grained control over the bundle available. (See this documentation for reference: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html)

Please let us know if you had any other questions regarding this topic.

**Comment by lorienpatt** [comment]
@tim-finnigan I'm not sure how default usage of Boto3 is not subject to the CVE.  Just adding boto3 to an application automatically adds botocore, those whl and tar files are automatically flagged by the National Vulnerability Database. 
Do you have any examples on how to use the configuration in the manner you are describing?  Not the boto3 config reference documentation, as it has no examples doing what you are asking for (`set their cert to with AWS_CA_BUNDLE in their environment vars or ca_bundle in the Config if they need finer grained control over the bundle available`).

**Comment by tim-finnigan** [comment]
Hi @lorienpatt - to control the certificates used you would need to configure it, which can be done using the environment variable `AWS_CA_BUNDLE` or use the `ca_bundle` profile parameter. Documentation is here:

* Env variable: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables
* Config file: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-a-configuration-file

Here you can find examples in the general SDK reference guide: https://docs.aws.amazon.com/sdkref/latest/guide/feature-gen-config.html. Have you tried using the Environment variable or config file approach?

**Comment by lorienpatt** [comment]
We don't use a specific AWS_CA_BUNDLE, we are just using the out of the box code samples.  Why would we need to use a custom certificate bundle?

**Comment by lorienpatt** [comment]
![Screen Shot 2022-12-19 at 3 14 55 PM](https://user-images.githubusercontent.com/23082230/208513299-6e621d13-f4a8-4779-b312-6ffbf1dae144.png)

**Comment by kdaily** [comment]
Hi @lorienpatt,

Hopefully I can provide some more clarifications to your questions.

> I'm not sure how default usage of Boto3 is not subject to the CVE. Just adding boto3 to an application automatically adds botocore, those whl and tar files are automatically flagged by the National Vulnerability Database.

`boto3` never uses the certificates mentioned in that CVE (those for TrustCor). In fact, it does not use any other certificates other than those to communicate with Amazon AWS services. So, despite the presence of those certificates, if you are using `boto3` in the supported manner, there is no risk because they are never used.

Any use of the certificate file provided with `botocore` other than that is not recommended and is at the users' own risk.

>  We also have the most up to date version of the certifi library installed, so I don't think its that.

This was noted by @tim-finnigan in a previous comment:

> Installing `certifi` supersedes anything in Botocore, this is the best general way to keep your certificates up to date, so we recommend that you keep your version of certifi up to date.

If you have the most up-to-date version of `certifi` installed, then the certificate file that comes with `botocore` is never used, even to communicate with AWS services, and there is nothing for you to do. The certificates provided by `certifi` are used instead.

> We don't use a specific AWS_CA_BUNDLE, we are just using the out of the box code samples. Why would we need to use a custom certificate bundle?

Some individuals and companies prefer to only use specific trusted certificates. In practice, this is a better way to control your risk tolerance. If you or the company you work for prefer to only use allowlisted certificates, setting them via the environment variable or configuration file parameter is the way to achieve that.

If these scenarios do not apply to you, then there isn't anything for you to do.

**Comment by lorienpatt** [comment]
Hi @kdaily,
I guess we don't have anything to do then.  Even though we are not affected by this, will you be working to get the package upgraded so NexusIQ will not flag this library?

**Comment by kdaily** [comment]
Hi @lorienpatt,

You're correct that you do not need to do anything. We're still investigating. Thanks!

**Comment by ulysses-31** [comment]
Hi

Botocore includes its own certificate authority (CA) file cacert.pem.  This cacert.pem file includes root certificates from "TrustCor" which are the cause of the CVE. Technically any CA listed in the included cacert.pem file can issue certificates for any DNS domain and will be trusted by software configured to use the cacert.pem for certificate validation. So any CA certs included must be very trust worthy.

A quick fix to resolve this CVE (including flagging in NexusIQ) would be to release a new version botocore with the root certificates from "TrustCor" removed from the botocore/cacert.pem file.

**Comment by tscheburaschka** [comment]
Hi, 
we also have this issue hitting us. The problem here is not that the normal usage of botocore would not trigger this vulnerability, but that in many deployment pipelines a NexusIQ scan is a mandatory security gate.
The flagged botocore package then needs to be reviewed manually.
If the cacert.pem-file delivered with your package would not include problematic certificates (or even better, only exactly the certificates you need) this issue would not come up and many people would not need to spend time understanding and assessing the risk involved.

So a fix in an upcoming version would be greatly appreciated.

**Comment by jeroenev** [comment]
Botocore is home to some pre-historic dependencies.
the jsonschema version is from 2015, which is starting to cause conflicts with other dependencies in my project which use newer versions of jsonschema.

**Comment by tim-finnigan** [comment]
Is this still an issue? There hasn't been any activity here in a while so wanted to confirm if this still applies to the latest botocore version (1.34.141 per the [CHANGELOG](https://github.com/boto/botocore/blob/develop/CHANGELOG.rst?plain=1)).
