### ISSUE TITLE
Paginator failure for Sitewise API - GetInterpolatedAssetPropertyValues

### ISSUE THREAD

**Issue by joysl** [boto/botocore#2874]
### Describe the bug

Customer is unable to use paginatorfor Sitewise API GetInterpolatedAssetPropertyValues

### Expected Behavior

Paginator should work printing paginated values when iterator is looped through

### Current Behavior

Receiving error:
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the GetInterpolatedAssetPropertyValues operation: The provided next token does not match query filtering parameters (Service: AWSIoTFlash; Status Code: 400; Error Code: InvalidRequestException; Request ID: 6150f55a-9798-406b-b946-d92a9dc40d0d; Proxy: null)

### Reproduction Steps

paginator = client.get_paginator('get_interpolated_asset_property_values') response_itr=paginator.paginate(
    assetId = "<>", 
    propertyId="<>", 
    type="LINEAR_INTERPOLATION", 
    intervalInSeconds=5,
    # startTimeInSeconds=1668988800,
    # endTimeInSeconds=11675775307,
    startTimeInSeconds=1675732107,
    # endTimeInSeconds=1677164775,
    # startTimeInSeconds=1675800720,
    endTimeInSeconds=1675732999,
    quality="GOOD", # default,
    # PaginationConfig={
#        'MaxItems': 10,
#        'PageSize': 10,
#        # 'StartingToken': nextToken
#    }
)
print(response_itr)
for page in response_itr:
    print(len(page['interpolatedAssetPropertyValues']))
    print(page['interpolatedAssetPropertyValues'])

### SDK version used

1.29.70

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by tim-finnigan** [comment]
Hi @joysl thanks for reaching out. As mentioned in your previous paginator request (https://github.com/boto/botocore/issues/2850), paginators are owned by service teams and therefore this issue would need to get rerouted to the IoT SiteWise team. A teammate advised us that you have already opened an internal ticket for that service team. That is the best way to escalate and track the issue going forward. I'm going to close this issue because I don't think it is necessary to track on GitHub as well. Feel free to message me if you have any questions related to this.
