### ISSUE TITLE
Paginator missing for Glue ListJobs API endpoint

### ISSUE THREAD

**Issue by danielward** [boto/botocore#2876]
### Describe the bug

The following code is not currently possible in botocore contrary to the API documentation for the underlying API endpoint.

```python
glue_client = boto3.client("glue")
paginator = glue_client.get_paginator("list_jobs")
```

### Expected Behavior

The expectation is that pagination should possible against `list_jobs` in the Glue client inline with the underlying API documentation, similarly to that of `get_jobs` (although of course the response data varies).

### Current Behavior

Execution of the code in the reproduction steps yields the following summarised exception:

```
botocore.exceptions.OperationNotPageableError: Operation cannot be paginated: list_jobs
```

### Reproduction Steps

The following logic should be possible through botocore:

```python
glue_client = boto3.client("glue")
paginator = glue_client.get_paginator("list_jobs")
```

### Possible Solution

Append the following to data/glue/2017-03-31/paginators-1.json (as demonstrated in https://github.com/danielward/botocore/commit/d1d7878ebdcd1aeee71bc7a22cdf9d293a22e434):

```json
"ListJobs": {
  "input_token": "NextToken",
  "limit_key": "MaxResults",
  "output_token": "NextToken",
  "result_key": "JobNames"
}
```

Following the above addition, the following code executes as expected (no `AssertionError` is raised) (I have confirmed that data is present in my investigation also, but redacted this from view here):

```python
import boto3

glue_client = boto3.client("glue")

paginator = glue_client.get_paginator("list_jobs")
iterator = paginator.paginate()

for page in iterator:
    assert isinstance(page["JobNames"], list)
```

### SDK version used

1.27.70

### Environment details (OS name and version, etc.)

macOS 13.2.1 (22D68)

**Comment by aBurmeseDev** [comment]
Hi @danielward - thanks for bringing this up! 

You're right that paginator isn't currently available for Glue client `ListJobs`, though you might be able to accomplish it with `GetJobs` [paginator](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#paginators) as they're similar enough unless you have a specific use case that you can share. 

Since we like to keep consistency between all SDKs, this would be a request that the service team needs to implement. I'm going to have to move this to our cross-sdk ([aws/aws-sdk](https://github.com/aws/aws-sdk)) repository and reach out to Glue service team with your specific use case to be considered.

Best,
John
