### ISSUE TITLE
assume_role and get_session_token unreachable code for TokenCode

### ISSUE THREAD

**Issue by kisst** [boto/botocore#2919]
### Describe the bug

The documentation for assume_role and get_session_token both suggest that the TokenCode can be passed in as a parameter while in practice the code does not validate the existence of the token code if mfa is used it promt for the TokenCode no matter what see: https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L826

### Expected Behavior

If TokenCode is part of the call, then it's used for the API calls and there is no interactive prompt for it.

### Current Behavior

Prompt even if it wouldn't be needed.

### Reproduction Steps

```
session = boto3.Session()
sts = session.client("sts")
response = sts.assume_role(
    RoleArn=arn,
    RoleSessionName=sessionname,
    SerialNumber=mfa_serial,
    TokenCode=totpcode
)
```

### Possible Solution

Either update the documentation and remove the option to pass the TokenCode or update the conditions for the promt

### Additional Information/Context

currently using `except` but it's a hack, want to go native

### SDK version used

latest

### Environment details (OS name and version, etc.)

linux

**Comment by tim-finnigan** [comment]
Hi @kisst thanks for reaching out. The documentation for those commands is pulled in from the API documentation, for example:
* [assume_role](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sts/client/assume_role.html#) / [AssumeRole](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html)
* [get_session_token](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sts/client/get_session_token.html#) / [GetSessionToken](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html)

Since those APIs are used across SDKs, any feedback on that documentation would need to go to the STS team.

If you're referring to the Assume role credential provider (documented here: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#assume-role-provider) then please let us know which part you think should be clarified or improved.
