### ISSUE TITLE
Stubber SQS send_message_batch expected param validation issue

### ISSUE THREAD

**Issue by Dmdl** [boto/botocore#2940]
### Describe the bug

Stubber always expects a "Failed" list for the response of a `send_message_batch` but AWS doesn't always return the "Failed" list.

### Expected Behavior

Stubber shouldn't expect "Failed" to be always part of the response.

### Current Behavior

We need to always pass "Failed", otherwise `ParamValidationError` exception is thrown.

```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Missing required parameter in input: "Failed"
```

### Reproduction Steps

```python
send_message_batch_response = {
    "Successful": [
        {
            "Id": "string",
            "MD5OfMessageAttributes": "string",
            "MD5OfMessageBody": "string",
            "MD5OfMessageSystemAttributes": "string",
            "MessageId": "string",
            "SequenceNumber": "string",
        }
    ]
}

send_message_batch_expected_params = {
    "Entries": [
        {
            "Id": "string",
            "MessageBody": "string",
            "MessageDeduplicationId": "string",
            "MessageGroupId": "string",
        }
    ],
    "QueueUrl": "test-queue",
}

sqs_client_stubber.add_response(
    "send_message_batch",
    send_message_batch_response,
    send_message_batch_expected_params,
)
```

### Possible Solution

Make "Failed" an optional field.

### SDK version used

1.29.80

### Environment details (OS name and version, etc.)

mac

**Comment by Dmdl** [comment]
A similar issue - https://github.com/boto/botocore/issues/1782

**Comment by tim-finnigan** [comment]
Hi @Dmdl thanks for reaching out. As mentioned [here](https://github.com/boto/botocore/issues/1782#issuecomment-521025516) in that related issue, the service team would need to address this because they maintain the implementation of their models which are used across SDKs. I created a new issue to track this here in our cross-SDK repository: https://github.com/aws/aws-sdk/issues/536. I reached out to the SQS team regarding this and will share any updates on that issue. Please refer to that issue for updates going forward, and thanks again for bringing our attention back to this.
