### ISSUE TITLE
SSO cache file hash incorrect

### ISSUE THREAD

**Issue by bisrael8191** [boto/botocore#2956]
### Describe the bug

When boto tries to load sso credentials from the JSON cache file, it generates a hash that doesn't match the filenames. It is looking for the file `59146b57f9acd0df73c13bbc6a53478be4ca6ca0.json` but the login command (`aws sso login`) generates different filenames.  

### Expected Behavior

Boto3 should be able to load the cached SSO credentials correctly.

### Current Behavior

Running any boto example returns the following exception:

```
Traceback (most recent call last):
  File "/Users/username/Documents/code/pyscript/venv/lib/python3.10/site-packages/botocore/credentials.py", line 322, in __getitem__
    with open(actual_key) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/username/.aws/sso/cache/59146b57f9acd0df73c13bbc6a53478be4ca6ca0.json'

...

botocore.exceptions.SSOTokenLoadError: Error loading SSO Token: The SSO access token has either expired or is otherwise invalid.
```

### Reproduction Steps

Login via SSO: `aws sso login`
Ensure that the cli works: `aws s3 ls`
Run a python example (hello amazon S3): https://docs.aws.amazon.com/code-library/latest/ug/python_3_s3_code_examples.html

### Possible Solution

Fix the hash algorithm in credentials.py [`SSOCredentialFetcher._create_cache_key(self)`] to match however the AWS cli creates the SSO cache filenames.

### SDK version used

boto3: 1.24.59, botocore: 1.27.59

### Environment details (OS name and version, etc.)

osx ventura, Version 13.0.1 (22A400)
python 3.10.4

**Comment by tim-finnigan** [comment]
Hi @bisrael8191 thanks for reaching out. Here is the boto3 documentation for using SSO (now IAM Identity Center): https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#aws-iam-identity-center.

Also referenced in that documentation is the AWS CLI documentation for configuring SSO: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html.

I think the first thing to rule out is that you have correctly configured SSO. In order to investigate further could you please share your debug logs (with any sensitive info redacted) by adding `boto3.set_stream_logger('')` to your script? I found another issue that might be related to this one, with more context on the caching behavior [provided here](https://github.com/boto/botocore/issues/2374#issuecomment-1045503565).
