### ISSUE TITLE
Old URLlib fails to install together with other projects

### ISSUE THREAD

**Issue by localagi** [boto/botocore#2963]
### Describe the bug

`#8 11.48 ERROR: botocore 1.29.146 has requirement urllib3<1.27,>=1.25.4, but you'll have urllib3 2.0.2 which is incompatible.`

### Expected Behavior

`pip install` works flawlessly

### Current Behavior

See above

### Reproduction Steps

- install any project requiring a more recent version of urllib
- try to add `botocore` as dependency

### Possible Solution

Update version at the line referenced in the issue

### SDK version used

see above

### Environment details (OS name and version, etc.)

ubuntu 22.04 x86_64

**Comment by tim-finnigan** [comment]
Hi @localagi thanks for reaching out. This issue is currently being tracked here: https://github.com/boto/botocore/issues/2926. The latest update was provided [here](https://github.com/boto/botocore/issues/2926#issuecomment-1554767670) two weeks ago:
>...We've seen there are a number of breaking cases in common workflows for AWS customers with the introduction of the new major version which has slowed how quickly we might move towards using urllib3 2.0 by default.
>
>Botocore is properly pinned for version support at the moment to limit unnecessary blast radius...

An per an [earlier comment](https://github.com/boto/botocore/issues/2926#issuecomment-1538900780) on that issue:
>We'd advise users to pin to urllib3<2 in their requirements or rely on the current pin in Botocore for the time being.

Please refer to that issue for updates going forward and let us know if you have any follow up questions.
