### ISSUE TITLE
Handle encoding of e-mail addresses in SES client

### ISSUE THREAD

**Issue by decibyte** [boto/botocore#2969]
### Describe the feature

It would be nice if the SES client took care of encoding both local part and domain of e-mail addresses, according to to what is expected by SES.

### Use Case

Severel times a day, I get errors when trying to send e-mails, because some of our users are registered with e-mail addresses that contain non-ASCII characters.

I've been trying to find information about how to encode the addresses properly, but I realise that:

1) It is not very well defined. And, more importantly:
2) It's a moving target. It has changed several times over recent years how I'm expected to encode e-mail addresses.

### Proposed Solution

Instead of leaving it to the user of boto to properly encode e-mail addresses according to whatever the expectations are on a given day, the library should do this when an e-mail address is passed on to it.

That way, users of boto would not have to update their own application code every time this changes. A simple upgrade of boto will do the trick. Also, this probably saves a lot of boto users some headaches :)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

boto3 1.26.151

### Environment details (OS name and version, etc.)

Docker image based on most recent python:3.11-slim-bullseye

**Comment by tim-finnigan** [comment]
Thanks @decibyte for the feature request. Unfortunately this is a limitation in the SES APIs that they would need to address, as the Boto3 [SES client commands](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ses.html) map directory to those APIs.

The [SendEmail](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendEmail.html) and [SendRawEmail](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html) API documentation pages have the following note:
>Amazon SES does not support the SMTPUTF8 extension, as described in [RFC6531](https://tools.ietf.org/html/rfc6531). For this reason, the email address string must be 7-bit ASCII. If you want to send to or from email addresses that contain Unicode characters in the domain part of an address, you must encode the domain using Punycode. Punycode is not permitted in the local part of the email address (the part before the @ sign) nor in the "friendly from" name. If you want to use Unicode characters in the "friendly from" name, you must encode the "friendly from" name using MIME encoded-word syntax, as described in [Sending raw email using the Amazon SES API](https://docs.aws.amazon.com/ses/latest/dg/send-email-raw.html). For more information about Punycode, see [RFC 3492](http://tools.ietf.org/html/rfc3492).

(This is also noted in the [SES guide](https://docs.aws.amazon.com/ses/latest/dg/troubleshoot-error-messages.html) on troubleshooting error messages.)

I'm not familiar with the history of changes with this functionality but I don't think there were any recent updates to it. However we can forward your feedback to the SES team if there are specific things regarding the documentation or suggested workarounds that you wanted to highlight.

**Comment by swpalmer-cl** [comment]
> However we can forward your feedback to the SES team if there are specific things regarding the documentation or suggested workarounds that you wanted to highlight.

Is there an open issue for the SES team to address supporting SMTPUTF8?  We are in a chicken and egg situation here.. The SES team seems to think this isn't significant because there is not enough demand, yet part of the reason there is not enough demand is because so many services rely on AWS SES which does not support it so we are forced to not use non-ASCII email addresses.
This is something that should "just work" .  SES should take care of doing the proper encoding when given a UTF-8 encoded email address.  SES needs to lead the charge here.

The existing documentation should also be clarified as the friendly display name is called out as something that can be MIME encode-word encoded, but that it in the same place that says everything before the '@' can't use Punycode so use MIME encode-word for the friendly name.... it neglects to point out that the local part of the address does not include the friendly name and cannot use MIME encode-words.
