### ISSUE TITLE
IAM GetAccountSummaryResponse return value enumeration is not complete

### ISSUE THREAD

**Issue by jcardali** [boto/botocore#3059]
### Describe the issue

We have observed the following additional keys:
- `AssumeRolePolicySizeQuota`
- `InstanceProfiles`,
- `InstanceProfilesQuota`
- `Providers`
- `RolePolicySizeQuota`
- `Roles`
- `RolesQuota`

### Links

`GetAccountSummaryResponse` - https://github.com/boto/botocore/blob/develop/botocore/data/iam/2010-05-08/service-2.json#L4188
`summaryMayType` - https://github.com/boto/botocore/blob/develop/botocore/data/iam/2010-05-08/service-2.json#L9127
`summaryKeyType` - https://github.com/boto/botocore/blob/develop/botocore/data/iam/2010-05-08/service-2.json#L9096

**Comment by tim-finnigan** [comment]
Thanks @jcardali for reporting this. Service API models are maintained by service teams and shared across SDKs, so I reached out to the IAM team regarding this issue. Because models are shared across SDKs, I created a new issue to track this in our cross-SDK repository: https://github.com/aws/aws-sdk/issues/646. Please refer to that issue for updates going forward.
