### ISSUE TITLE
botocore still ignore "HTTP/1.1 100"  

### ISSUE THREAD

**Issue by kbgksj** [boto/botocore#3149]
### Describe the bug

**Related Issue**
- https://github.com/boto/botocore/issues/1943 
- https://github.com/boto/botocore/issues/1931 

I think botocore still ignore "HTTP/1.1 100" that does not contain reason-phrase content (Continue).
Is there any reason?

### Expected Behavior

When a s3 server returns 100 Status code without reason phrase (Continue), 
boto3 should work without errors. 

### Current Behavior

boto3 raises errors ( botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL ) 

### Reproduction Steps

1.  Run boto3's put_object function to a custom endpoint_url (custom s3 server)
2.  If a custom s3 server returns 100 code without reason phrase, the client (boto3) raises errors

### Possible Solution

change one of the following functions in awsrequest.py (https://github.com/boto/botocore/blob/develop/botocore/awsrequest.py)
- _is_100_continue_status
- _handle_expect_response

### SDK version used

Version: 1.34.73

### Environment details (OS name and version, etc.)

Redhat 7.9

**Comment by tim-finnigan** [comment]
Thanks for bringing this issue back to our attention. It looks like the original issue auto-closed due to lack of activity. I can reopen that one to continue tracking and bring it up with the team for discussion. It looks like a PR was submitted for this (https://github.com/boto/botocore/pull/1932) but the team decided to close it and its not clear why. Please refer to that original issue for updates going forward.
