### ISSUE TITLE
Paginators should respect the page size limits of operations, and should clamp the user's request for page sizes outside of the limits.

### ISSUE THREAD

**Issue by rustyconover** [boto/botocore#3260]
### Describe the bug

When setting a `PageSize` for a `PaginatorConfig`, `botocore` should respect the min/max limits if they exist in the metadata of the limit key.  

If a user requests a `PageSize` outside the bounds, it should be constrained to be in bounds.

### Expected Behavior

I expected a request for 10,000 items per page to be clamped to the limit of the operation's `limit_key`.

### Current Behavior

No clamping is done of the page value and the API request fails because the requested number of items is greater than what the API can provide.

### Reproduction Steps

# See PR

### Possible Solution

See PR https://github.com/boto/botocore/pull/3259

### SDK version used

1.35.5

### Environment details (OS name and version, etc.)

Mac OS X

**Comment by tim-finnigan** [comment]
Thanks for reaching out and creating that PR. Unfortunately we cannot accept the PR, because we do not do client-side validation on the pagination parameters — those are validated by service APIs. For example:
> botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the ListTables operation: 1 validation error detected: Value '200' at 'limit' failed to satisfy constraint: Member must have value less than or equal to 100

Also as noted in the [other issue](https://github.com/boto/botocore/issues/3261) you opened, there are some inconsistencies among service API models. There are no plans to change the existing behavior here.
