### ISSUE TITLE
Extend ssm command-executed waiter to wait for all instances targeted by a command

### ISSUE THREAD

**Issue by arianvp** [boto/botocore#3269]
### Describe the feature

```
aws ssm wait command-executed --command-id $id
```

waits for the entire command to be executed on all instances it targets

(Maybe we should rename the original waiter to `wait command-invocation-executed`

### Use Case

With https://github.com/boto/botocore/issues/1744 we can wait for a command to be executed on a single instance; however the SSM API has evolved and it's possible to send a command to multiple targets at the same time:

```
aws ssm send-command --document-name my-doc --targets 'key=tag:Name,values=my-servers' --query 'Command.CommandID'
```

I want to wait for all of the instances with `Name=my-servers`

### Proposed Solution

The waiter should watch `ssm:ListCommands(CommandId=id)` until `Commands[0].Status=Success`

### Other Information

My current workaround:

```
       tries=24
          while true; do
            sleep 5
            if [ $tries -eq 0 ]; then
              echo "Command did not finish in time"
              exit 0
            fi
            status=$(aws ssm list-commands \
                --command-id ${{ steps.send-command.outputs.command_id }} \
                --query "Commands[0].Status" \
                --output text)
            
            # if pending or in progress, or cancelling
            if [ "$status" = "Pending" ] || [ "$status" = "InProgress" ] || [ "$status" = "Cancelling" ]; then
              tries=$((tries-1))
              continue
            fi
            break
          done
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

aws-cli/2.17.56

### Environment details (OS name and version, etc.)

MacOS

**Comment by tim-finnigan** [comment]
Thanks for the feature request. Waiter models are created and maintained upstream by service teams, as they are used across AWS SDKs. It looks like CommandExecuted has been the only SSM waiter for a while:
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ssm/wait/index.html#cli-aws-ssm-wait
* https://github.com/boto/botocore/blob/develop/botocore/data/ssm/2014-11-06/waiters-2.json

To what extent does your request overlap with https://github.com/boto/botocore/issues/1744 / https://github.com/aws/aws-sdk/issues/90 ? Here is the related PR that was written: https://github.com/boto/botocore/pull/1753/files. The SSM team is still tracking the request to add this waiter, but it hasn't been prioritized. I can try checking in with them regarding this.

But I don't think the request to update a waiter's name or polling logic would be considered because of the need to maintain backwards compatible behavior. If you can, please let me know specifically what model changes you are proposing and I can share that with the SSM team.

**Comment by arianvp** [comment]
> To what extent does your request overlap with https://github.com/boto/botocore/issues/1744 / https://github.com/aws/aws-sdk/issues/90 ? Here is the related PR that was written: https://github.com/boto/botocore/pull/1753/files. The SSM team is still tracking the request to add this waiter, but it hasn't been prioritized. I can try checking in with them regarding this.

Not at all. That PR you link is the exact same code as the `command-executed` waiter. 

The thing I am proposing is ability to wait for a command to finish instead of a specific command-invocation.

A single command can have many invocations (e.g. when targeting multiple instances using  tags). I want to wait until the *entire command* is finished; not just a single invocation.   When you do an `aws ssm run-command --targets Name=tag:Name,Values=mytag` you don't get a list of instance ids back so there is no way to use the existing `aws ssm wait command-executed` waiter

**Comment by indranil32** [comment]
Is this resolved ? Can we add "wait" in aws ssm command-executed ?

**Comment by arianvp** [comment]
No it's not resolved.
