### ISSUE TITLE
ModifyDBInstance missing CACertificateIdentifier?

### ISSUE THREAD

**Issue by Jc2k** [boto/botocore#473]
Amazon sent an e-mail saying to update CACertificateIdentifier to rds-ca-2015 to avoid service interruptions. It would be good to be able to do this programatically.

**Comment by kyleknap** [comment]
It looks like we need to update our RDS model since they expose it in their API.

Here is the current api references for ModifyDBInstance (notice the CACertificateIdentifier parameter, which is what the console is probably using):
http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBInstance.html

It also looks like you can describe the certificates as well:
http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeCertificates.html

I will look into updating this.

**Comment by JordonPhillips** [comment]
Closing this out since it has been since added to the SDK. [docs](http://boto3.readthedocs.org/en/latest/reference/services/rds.html#RDS.Client.modify_db_instance)
