### ISSUE TITLE
result_keys or result_keys_iter

### ISSUE THREAD

**Issue by rdbhost** [boto/botocore#480]
Can anyone provide a use-case for the result_keys method?

I am porting botocore to asyncio; while most methods are just line-by-line conversions, changing 'obj.method()' to 'yield from obj.method()', the use of iterators in the original requires some re-architecting.   Asyncio coroutines repurpose the yield mechanism, so you can't 'yield [meaningful value] 'from a coroutine.

Converting iterators would take one of two forms:
1) preload all the async data, and return a regular list iterator.
2) change iterator to an archaic-seeming 'while r: r = yield from obj.next()' type iterator.

The first allows maintaining the user's code sequencing, at the cost of (possibly extreme) slowness.
The second requires the user to change their code, but allows iterative or partial downloading.

A use-case or two for the result_keys methods would help in deciding on an approach.

David

**Comment by kyleknap** [comment]
@rdbhost 

``result_keys`` method is to get the result_keys from the pagination model. So here is s3's pagination model: https://github.com/boto/botocore/blob/develop/botocore/data/aws/s3/2006-03-01.paginators.json. It pretty much says what element in the response we are paginating for. So for ListObjects we are paginating for CommonPrefixes and Contents (which are the keys).

``result_keys_iter`` Allows use to return iterators for the values of the result_keys in the response. Note that since you can have more than one result_keys in the model, you can have more than one iterator returned by this method (one for each result_key).

As to choosing one iterator conversion over the other, we will think about it and get back to you. Just wanted to at least answer your initial question.

**Comment by jamesls** [comment]
If (1) is only preloading a single response and *not* the entire aggregation of all response pages, then I think 1 seems fine.  However if (1) is preloading all of the response pages first, then I would suggest against that approach.  That has potentially to be really large.

Please let us know if you have any more questions.
