### ISSUE TITLE
UserData should have a Blob shape

### ISSUE THREAD

**Issue by charleso** [boto/botocore#521]
As far as I can tell [RunInstances.userData](https://github.com/boto/botocore/blob/develop/botocore/data/aws/ec2/2014-10-01.normal.json#L10302) (and probably other cases) needs to be base64 encoded and (I think) therefore should have a shape of "Blob"? An example of a base64 encoded member that does have Blob is [PublicKeyMaterial](https://github.com/boto/botocore/blob/develop/botocore/data/aws/ec2/2014-10-01.normal.json#L6655).

I'm happy to raise a PR to fix the json, but it sounds like it's better to raise an issue. Thanks in advance.

**Comment by kyleknap** [comment]
@charleso 

Yeah you are correct about the userData parameter needing to be modeled as a blob. To compensate, we actually have a handler: https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L383 that will base64 encode the user data for you. Are you seeing the data not getting base64 encoded from your side?

Otherwise thanks for the offer to fix it.

**Comment by charleso** [comment]
https://github.com/boto/botocore/pull/522

**Comment by kyleknap** [comment]
As I mention in my comment for https://github.com/boto/botocore/pull/522, we will look into updating the upstream source to use blobs as opposed to strings to model UserData.

**Comment by charleso** [comment]
@kyleknap No worries. I misinterpreted the "thanks for the offer" part of your message. :) Apologies for the noise.

**Comment by jamesls** [comment]
Closing out issue as per @kyleknap [comment](https://github.com/boto/botocore/issues/521#issuecomment-94861165)
