### ISSUE TITLE
Paginators are needed for logstream items

### ISSUE THREAD

**Issue by eldondevcg** [boto/botocore#613]
I think the following items in the cloudwatch "logs" resource need paginators:
describe_log_groups
describe_log_streams
describe_metrics_filters
describe_subscription_filters
filter_log_events
get_log_events

**Comment by kyleknap** [comment]
Marking as feature request.

**Comment by mjschultz** [comment]
I have a [PR](https://github.com/boto/botocore/pull/627) that adds paginators for *most* of those except `get_log_events`.

`get_log_events` is a bit weird because it returns both a `nextForwardToken` and a `nextBackwardToken` and the one you'd want to use depends on if you set `startFromHead` or not. The token itself is also different from other APIs in that the `next*Token` will be a repeat on the last page (and the `events` list will be empty). So I'm not sure of the best way to handle that.

All that said, I'd rather have the other paginations in with that one missing then follow up with the `get_log_events` down the road.

**Comment by jamesls** [comment]
Closing out issue, #627 has been merged.  We'll need to address get_log_events later on down the road.
