### ISSUE TITLE
Pin jmespatch dependency version

### ISSUE THREAD

**Issue by BrianEWhipple** [boto/botocore#656]
Can this library pin its jmespath dependency to a specific version?  Currently, it depends on the development branch of the jmespath GitHub repo - which is not stable nor deterministic.

Currently, this project's setup.py requires version 0.7.1 but the upstream GitHub repo/branch does not deliver that version - so this project's dependency graph is disconnected.

This can result in runtime errors for downstream consumers - like my organization did today.

**Comment by jamesls** [comment]
Could you elaborate on what runtime errors you encountered?  I'd like to understand how this is breaking  downstream consumers before fixing.  The only place we reference the dev branch of jmespath is in the requirements.txt file, which we only use for running our tests.  `pip install botocore` will always pull in the locked version of jmespath from the setup.py.

**Comment by BrianEWhipple** [comment]
Today we started getting runtime errors:

    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jmespath==0.7.1' distribution was not found and is required by botocore

Version 0.8.0 of jmespath was being installed into our site-packages instead of 0.7.1.  I'm not sure exactly how pip manages transitive dependencies - I'll poke into that more and try to find the root problem.

I should have also mentioned that we pin our version of botocore to 1.1.6.

**Comment by jamesls** [comment]
Ok.  I think the problem is that because botocore has a dependency that's too strict, if something else pulls in a newer jmespath then you'll run into this problem.  Pip doesn't seem to handle this well, for example, in a fresh virtualenv, if I install botocore, then boto3 I get:

```
$ pip install botocore boto3
Successfully installed boto3-1.1.3 botocore-1.2.4 docutils-0.12 futures-2.2.0 jmespath-0.7.1 python-dateutil-2.4.2 six-1.9.0
$ python -c "import jmespath; print jmespath.__version__"
0.7.1
```

When I reverse the order, I get:

```
$ pip install boto3 botocore
Successfully installed boto3-1.1.3 botocore-1.2.4 docutils-0.12 futures-2.2.0 jmespath-0.8.0 python-dateutil-2.4.2 six-1.9.0
$ python -c "import jmespath; print jmespath.__version__"
0.8.0
```

What I would propose if relaxing the version constraint here.  botocore doesn't actually need thing that's only in v0.7.1 so if change this to be the same as boto3, that is: `jmespath>=0.6.2,<1.0.0` this should fix the issue.

**Comment by jamesls** [comment]
Also reported in: https://github.com/boto/boto3/issues/270
