### ISSUE TITLE
param VpcSecurityGroupIds missing in RestoreDBClusterFromSnapshot

### ISSUE THREAD

**Issue by henrysher** [boto/botocore#708]
Hi, 

I think it is a compatible issue which makes my script failed in the production, really critical.
Could you please help check it?

Since @rayluo deleted this param on Oct 2nd, in the commit: https://github.com/boto/botocore/commit/ad67c4fee319221381fa9dcfe67335c392dd23fd.
However, according to the latest API document, there is no such change, VpcSecurityGroupIds still exists: http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBClusterFromSnapshot.html. 

Thanks
Henry

**Comment by kyleknap** [comment]
Shoot that is a mistake. We will get this added back.

**Comment by kyleknap** [comment]
@henrysher 
I was going through our model and RestoreDBClusterFromSnapshot has VpcSecurityGroupIds: https://github.com/boto/botocore/blob/develop/botocore/data/rds/2014-10-31/service-2.json#L8906.

Did you mean the removal of VpcSecurityGroupsIds from RestoreDBInstanceFromDBSnapshot? https://github.com/boto/botocore/commit/ad67c4fee319221381fa9dcfe67335c392dd23fd#diff-95c79054999adb6cdb2ab1ae8183d408L9156 because that is not in their documentation: http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBInstanceFromDBSnapshot.html.

Let me know what exactly is breaking in your scripts.

**Comment by majinjing3** [comment]
Hi, I have checked between 
https://github.com/boto/botocore/blob/ad67c4fee319221381fa9dcfe67335c392dd23fd/botocore/data/rds/2014-10-31/service-2.json (Oct 2 changed)
and
https://github.com/boto/botocore/blob/26b7810e509c4e9ffa7aa79f04d068cbe0c4971f/botocore/data/rds/2014-10-31/service-2.json (Jul 31 changed)

in RestoreDBInstanceFromDBSnapshot function, the VpcSecurityGroupIds paramater has been deleted.

I know in http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBInstanceFromDBSnapshot.html page, there is no VpcSecurityGroupIds paramater in RestoreDBInstanceFromDBSnapshot. 
but, in previous code, we used it. 
So, you change have some side effect for us. we just confirm it now.

Thanks.
Jim Ma

**Comment by jamesls** [comment]
We've confirmed with the RDS team that these changes are not ready for general use.  We don't have an ETA when these features will be generally available.  We are sorry for any inconvenience this has caused you.  I'm going to go ahead and close this issue out.  Please let us know if you have other questions we can answer.
