### ISSUE TITLE
Cloudformation Paginator PageSize does not work

### ISSUE THREAD

**Issue by gimbel0893** [boto/botocore#876]
We're trying to use page size with the CloudFormation paginator.  We're having the following issue.

Example code:
client = boto3.client('cloudformation')
paginator = client.get_paginator('list_stacks')
for page in paginator.paginate(StackStatusFilter=['CREATE_COMPLETE'], PaginationConfig={'PageSize': 1}):
  ......

Will throw error:
.....
botocore/paginate.py", line 175, in _make_request
    return self._method(**current_kwargs)
TypeError: _api_call() keywords must be strings

We've traced it down to _limit_key being None, which is used in a kargs dictionary.  So you get {None: 1} (assuming 1 was the PageSize arg sent earlier).

Guessing what _limit_key string should be, we always get unexpected parameter (below trying _limit_key="PageSize'):
Unknown parameter in input: "PageSize", must be one of: NextToken, StackStatusFilter

Using
boto3==1.3.0
botocore==1.4.11

Are you able to reproduce?
Thanks,
Mike

**Comment by kyleknap** [comment]
Yeah I am able to reproduce. The reason is because the ``list_stacks`` operation does not have a max items related parameter to map the PageSize argument to: https://botocore.readthedocs.org/en/latest/reference/services/cloudformation.html#CloudFormation.Client.list_stacks. So in short there is not really a way to use page size because the api does not support it.


Here is what I was getting:
```
Traceback (most recent call last):
  File "foo.py", line 6, in <module>
    for page in paginator.paginate(StackStatusFilter=['CREATE_COMPLETE'], PaginationConfig={'PageSize': 1}):
  File "/Users/kyleknap/GitHub/botocore/botocore/paginate.py", line 104, in __iter__
    response = self._make_request(current_kwargs)
  File "/Users/kyleknap/GitHub/botocore/botocore/paginate.py", line 176, in _make_request
    return self._method(**current_kwargs)
TypeError: _api_call() keywords must be strings
```
I think that this is a pretty confusing error. We will to improve the error message and the docs.

**Comment by gimbel0893** [comment]
Sorry on the late response.  Thanks much for looking.

Oh ok, we were looking at the paginator documentation.
https://botocore.readthedocs.org/en/latest/reference/services/cloudformation.html#CloudFormation.Paginator.ListStacks
