### ISSUE TITLE
Feature Request: Strict validation for stub responses

### ISSUE THREAD

**Issue by plumdog** [boto/botocore#949]
WAF's IPSet appears to be missing some validation:

Running

``` python
from botocore.stub import Stubber
import botocore.session

client = botocore.session.get_session().create_client('waf', region_name='us-west-2')


stub = Stubber(client)
stub.add_response(
    'get_ip_set',
    expected_params={'IPSetId': 'my-ip-set-id'},
    service_response={'IPSet': {
        'IPSetId': 'my-rule-id',
        'IPSetDescriptors': [{'Type': 'a', 'Value': 'b'}]
    }},
)

with stub:
    client.get_ip_set(IPSetId='my-ip-set-id')
```

exits cleanly (using `botocore==1.4.27`), with no exception being raised. I would expect it to complain because the IPSetDescriptor's `Type` and `Value` only have limited things they can be. The metadata [knows that `Type` must be `'IPV4'`](https://github.com/boto/botocore/blob/develop/botocore/data/waf/2015-08-24/service-2.json#L1546). It doesn't appear to know that `Value` has to be a CIDR block, but the docs do.

I believe that the Stubber just uses the generic validation, so this suggests to me that the validation doesn't make any use of the `enum` declaration in the metadata and this may be a more widespread problem. The CIDR block looks a bit more tricky, but it would be lovely it there was validation against it too.

**Comment by jamesls** [comment]
That's an interesting point.  In "real" botocore clients (i.e not the stubber), we purposefully do not validate enums so that if a service adds a new valid enum value, you can still use older versions of botocore with the new enum value without requiring an upgrade of botocore/boto3.

However, it might be worth adding (or opting in to) additional validation when using the stubber.  This does have the same root issue though, you'll need to upgrade botocore if the service adds a new enum value that you want to use in your tests that leverage the stubber.

Thoughts? cc @JordonPhillips @kyleknap

**Comment by JordonPhillips** [comment]
It seems like something that could be useful when you're actively writing tests, but it's a big risk. We could mitigate the risk somewhat by logging a warning when the validate fails, but it still makes me uneasy.

**Comment by jamesls** [comment]
I don't know if I agree that it's a "big" risk.

The two mitigating factors for me:

* This is opt in.  A customer would have to opt in, acknowledging that this may cause issues if you want to use new enum values in the future without upgrading.
* The failure mode is in tests.  This won't  break production code, only testing code.  You'd always have reasonable mitigations: turn this option off in your tests or upgrade botocore.

Does that alleviate your concerns?

**Comment by Jc2k** [comment]
I've just started using Stubber myself and I agree with @plumdog - i would have expected `enum`'s to be validated.

The most appealing aspect of the Stubber for me is that it makes it that bit harder to get my fake responses wrong. If I had to choose between maybe having passing tests that shouldn't or maybe having brittle tests, I would choose to have brittle tests every time.

I also value the verbosity of error messages from the validation - the API's themselves are not universally helpful (though some are better than others).

For some of your customers (I guess low level ones like awscli) then validation can get in the way (because there is a limit on how quickly you can ship new metadata etc). I agree that enum validation here might be more annoying than its worth.

But I'm one of another type. I'm unlikely to be targeting the entire AWS API, and i'm not targeting the bleeding edge. I'm targeting tried and tested API's. If a new flag is added to an API I probably don't care for my existing code, and if i do i'm not going to be targetting it with my code until i've tested it out. And if I need to update botocore, so be it.

**Comment by JordonPhillips** [comment]
I suppose if we make it opt in, and put up a **bunch** of explicit warnings I would be +1 on this. @jamesls makes a good point that this is in tests, so production code isn't breaking. We could also catch the `ValidationError` in the stubber, log a warning if 'strict mode' is enabled, then re-raise it. That would help point customers to the fact that an update may be required, or otherwise 'strict mode' should be disabled.
